//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HomeUI/HUQuickControlController.h>

@class HFTemperatureThresholdControlItem;

@interface HUQuickControlTemperatureController : HUQuickControlController
{
}

+ (Class)controlItemClass;
+ (_Bool)matchesControlItem:(id)arg1;
- (id)controlToViewValueTransformer;
- (id)viewProfile;
- (id)createInteractionCoordinator;

// Remaining properties
@property(readonly, nonatomic) HFTemperatureThresholdControlItem *controlItem; // @dynamic controlItem;

@end

