//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDate.h>

@interface NSDate (ABNSDateAdditions)
+ (id)_ab_dateFromDateComponents:(id)arg1;
- (double)_ab_timeIntervalSinceJanuary1;
- (id)_ab_componentsForJanuary1InTheSameYear;
@end

