//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsCore/FCDraftsFeedGroupEmitter.h>

@interface FCDraftCoverStoriesGroupEmitter : FCDraftsFeedGroupEmitter
{
}

- (_Bool)emitsSingletonGroups;
- (id)groupEmitterIdentifier;
- (id)operationToEmitGroupWithContext:(id)arg1 fromCursor:(id)arg2 toCursor:(id)arg3;
- (_Bool)wantsToEmitGroupInContext:(id)arg1 withCursor:(id)arg2 toCursor:(id)arg3;

@end

