//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NewsCore/FCHeadlineClustering-Protocol.h>

@class FCHeadlineClusteringRules, FCSolHeuristic, NSDictionary, NSSet, NSString;

@interface FCHeadlineClusteringSol : NSObject <FCHeadlineClustering>
{
    FCHeadlineClusteringRules *_rules;
    NSSet *_subscribedTagIDs;
    NSSet *_articleIds;
    NSDictionary *_articlesByTag;
    NSDictionary *_tagsByArticle;
    NSDictionary *_articleScoresByTag;
    NSDictionary *_headlinesById;
    NSSet *_groupableTags;
    NSSet *_hardOrphans;
    FCSolHeuristic *_heuristic;
}

@property(retain, nonatomic) FCSolHeuristic *heuristic; // @synthesize heuristic=_heuristic;
@property(retain, nonatomic) NSSet *hardOrphans; // @synthesize hardOrphans=_hardOrphans;
@property(retain, nonatomic) NSSet *groupableTags; // @synthesize groupableTags=_groupableTags;
@property(retain, nonatomic) NSDictionary *headlinesById; // @synthesize headlinesById=_headlinesById;
@property(retain, nonatomic) NSDictionary *articleScoresByTag; // @synthesize articleScoresByTag=_articleScoresByTag;
@property(retain, nonatomic) NSDictionary *tagsByArticle; // @synthesize tagsByArticle=_tagsByArticle;
@property(retain, nonatomic) NSDictionary *articlesByTag; // @synthesize articlesByTag=_articlesByTag;
@property(retain, nonatomic) NSSet *articleIds; // @synthesize articleIds=_articleIds;
@property(retain, nonatomic) NSSet *subscribedTagIDs; // @synthesize subscribedTagIDs=_subscribedTagIDs;
@property(retain, nonatomic) FCHeadlineClusteringRules *rules; // @synthesize rules=_rules;
- (void).cxx_destruct;
- (id)clusterHeadlinesByTopic:(id)arg1 subscribedTopicIDs:(id)arg2 rules:(id)arg3;
- (id)computeBestGrouping:(id)arg1 subscribedTagIDs:(id)arg2 articleScoresByTag:(id)arg3 headlinesById:(id)arg4;
- (void)computeGrouping:(id)arg1 topK:(double)arg2;
- (id)computeBestMoveWithTag:(id)arg1 groupableArticles:(id)arg2 solos:(id)arg3 ungroupedArticles:(id)arg4 remainingTags:(id)arg5 groups:(id)arg6 topK:(double)arg7;
- (void)createMoveWithTag:(id)arg1 articles:(id)arg2 remainingTags:(id)arg3 ungroupedArticles:(id)arg4 moves:(id)arg5 groups:(id)arg6;
- (id)computeNewOrphansWithUngroupedArticles:(id)arg1 remainingTags:(id)arg2;
- (id)generateCombosWithSet:(id)arg1 tag:(id)arg2 chooseSize:(long long)arg3;
- (id)sortedScoredArticles:(id)arg1 tag:(id)arg2 length:(long long)arg3 asc:(_Bool)arg4;
- (id)scoredArticleWithID:(id)arg1 tag:(id)arg2;
- (double)computeGroupingUtility:(id)arg1;
- (double)weightedScoreForArticle:(id)arg1 tag:(id)arg2;
- (double)normalizedAboutnessForArticle:(id)arg1 tag:(id)arg2;
- (double)personalizationScoreForArticle:(id)arg1;
- (void)filterOverflowedOrphans:(id)arg1;
- (void)optimizeForLayout:(id)arg1;
- (void)mergeGroups:(id)arg1;
- (void)regroupOrphans:(id)arg1;
- (id)assignArticles:(id)arg1 groups:(id)arg2 maxClusterSize:(long long)arg3;
- (_Bool)reassignedArticleInGroups:(id)arg1 withTag:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

