//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FCOperationTime : NSObject
{
    double _totalTime;
    double _networkTime;
    double _nonNetworkTime;
}

+ (id)timeWithAverages:(id)arg1;
@property(nonatomic) double nonNetworkTime; // @synthesize nonNetworkTime=_nonNetworkTime;
@property(nonatomic) double networkTime; // @synthesize networkTime=_networkTime;
@property(nonatomic) double totalTime; // @synthesize totalTime=_totalTime;
- (id)description;

@end

