//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NewsTransport/NTPBArticleRecord.h>

@class NSArray;

@interface NTPBArticleRecord (FCAdditions)
@property(readonly, nonatomic) NSArray *endOfArticleTopicIDs;
- (id)generateWebExcerptAssetHandleWithAssetManager:(id)arg1;
- (id)generateFlintDocumentAssetHandleWithAssetManager:(id)arg1;
- (id)generateThumbnailAssetHandleForURL:(id)arg1 withAssetManager:(id)arg2;
@end

