//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAttributedString, NSDictionary, NSMutableDictionary, NSTextStorage, _IMKCandidateController;

@interface _IMKCandidateTextAttributes : NSObject
{
    _IMKCandidateController *_controller;
    NSTextStorage *_sharedTextStorage;
    NSDictionary *_mainAttributes;
    NSDictionary *_guideNumberAttributes;
    NSDictionary *_groupLabelAttributes;
    NSMutableDictionary *_sizeCalculationDictionary;
    NSAttributedString *_noteMark;
    NSAttributedString *_dictionaryMark;
    double _singleCharWidth;
}

@property(retain, nonatomic) NSMutableDictionary *sizeCalculationDictionary; // @synthesize sizeCalculationDictionary=_sizeCalculationDictionary;
- (struct CGSize)optimizedSizeForCJKStringWithMainAttributes:(id)arg1 length:(long long)arg2;
@property(readonly, nonatomic) double singleCharWidth; // @synthesize singleCharWidth=_singleCharWidth;
- (double)groupLabelWidth;
- (double)trailingMargin;
- (double)noteIconWidth;
- (double)textTrailingMargin;
- (double)textLeadingMargin;
- (double)guideNumberWidth;
- (double)leadingMargin;
- (double)cellHeight;
@property(readonly, nonatomic) NSAttributedString *dictionaryMark; // @synthesize dictionaryMark=_dictionaryMark;
@property(readonly, nonatomic) NSAttributedString *noteMark; // @synthesize noteMark=_noteMark;
@property(readonly, nonatomic) NSDictionary *groupLabelAttributes; // @synthesize groupLabelAttributes=_groupLabelAttributes;
@property(readonly, nonatomic) NSDictionary *guideNumberAttributes; // @synthesize guideNumberAttributes=_guideNumberAttributes;
@property(readonly, nonatomic) NSDictionary *mainAttributes; // @synthesize mainAttributes=_mainAttributes;
@property(readonly, nonatomic) NSTextStorage *sharedTextStorage; // @synthesize sharedTextStorage=_sharedTextStorage;
- (void)fontChanged;
- (void)dealloc;
- (void)_releaseAllAttributes;
- (id)initWithController:(id)arg1;

@end

