//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <InputMethodKit/CJKCandidateIndexing-Protocol.h>

@class NSString;

@interface CJKCandidateDefinitionUnit : NSObject <CJKCandidateIndexing>
{
    NSString *_text;
    NSString *_annotation;
    BOOL _hasDefinition;
    BOOL _hasNote;
}

@property(copy, nonatomic) NSString *annotation; // @synthesize annotation=_annotation;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic) BOOL hasNote; // @synthesize hasNote=_hasNote;
@property(nonatomic) BOOL hasDefinition; // @synthesize hasDefinition=_hasDefinition;
@property(readonly, nonatomic) NSString *axHelpString;
@property(readonly, nonatomic) NSString *axValueString;
- (void)dealloc;
- (id)descriptionHTMLAndBaseURL:(id *)arg1;
@property(readonly, nonatomic) NSString *uniqueKey;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

