//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class CJKCandidateController, CJKCandidateStepperAccessoryImageView;

@interface CJKCandidateStepperView : NSView
{
    CJKCandidateController *_candidateController;
    CJKCandidateStepperAccessoryImageView *_topArrowView;
    CJKCandidateStepperAccessoryImageView *_bottomArrowView;
    BOOL _initialized;
}

@property(nonatomic) BOOL initialized; // @synthesize initialized=_initialized;
@property(retain, nonatomic) CJKCandidateStepperAccessoryImageView *topArrowView; // @synthesize topArrowView=_topArrowView;
@property(retain, nonatomic) CJKCandidateStepperAccessoryImageView *bottomArrowView; // @synthesize bottomArrowView=_bottomArrowView;
@property(retain, nonatomic) CJKCandidateController *candidateController; // @synthesize candidateController=_candidateController;
- (void)setBottomStepperState:(BOOL)arg1;
- (void)setTopStepperState:(BOOL)arg1;
- (void)setupArrows;
- (void)changeArrowFrames;
- (struct CGRect)bottomArrowRectWithFrame:(struct CGRect)arg1;
- (struct CGRect)topArrowRectWithFrame:(struct CGRect)arg1;
- (struct CGRect)stepperAreaFrame;
- (void)setFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

