//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <OpenDirectoryConfig/ODCAction.h>

@class NSString;

@interface ODCUnbindFromADAction : ODCAction
{
    NSString *_userName;
    NSString *_password;
    BOOL _removeDomainFromSearchPaths;
    BOOL _forceUnbind;
}

@property BOOL removeDomainFromSearchPaths; // @synthesize removeDomainFromSearchPaths=_removeDomainFromSearchPaths;
@property BOOL forceUnbind; // @synthesize forceUnbind=_forceUnbind;
@property(copy) NSString *password; // @synthesize password=_password;
@property(copy) NSString *userName; // @synthesize userName=_userName;
- (void)startExecution;
- (void)legacyUnbind;
- (void)unbind;
- (id)init;

@end

