//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreWLANKit/UTF8Formatter.h>

@interface WEPKeyFormatter : UTF8Formatter
{
}

+ (id)wepKeyFormatter:(int)arg1;
+ (id)sharedWEPKeyFormatter;
- (BOOL)isPartialStringValid:(id)arg1 newEditingString:(id *)arg2 errorDescription:(id *)arg3;

@end

