//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SocialUI/NSObject-Protocol.h>

@class DOMElement, IMAssociatedMessageChatItem;

@protocol AssociatedMessageDOMProvider <NSObject>
- (void)parseAssociatedChatItem:(IMAssociatedMessageChatItem *)arg1 appendToElement:(DOMElement *)arg2 withChatItemElement:(DOMElement *)arg3;
@end

