//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SocialUI/NSCollectionViewDataSource-Protocol.h>

@class IMTranscriptCollectionViewLayout, IMTranscriptItem, NSIndexPath;

@protocol IMTranscriptCollectionViewLayoutDelegate <NSCollectionViewDataSource>
- (void)collectionViewLayout:(IMTranscriptCollectionViewLayout *)arg1 sizeDidChange:(struct CGSize)arg2;
- (void)collectionViewLayoutRestingDidChange:(IMTranscriptCollectionViewLayout *)arg1;
- (IMTranscriptItem *)collectionView:(struct NSCollectionView *)arg1 layout:(IMTranscriptCollectionViewLayout *)arg2 transcriptItemForItemAtIndexPath:(NSIndexPath *)arg3;
@end

