//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SocialUI/NSObject-Protocol.h>

@class SOBuddyOutlineView;

@protocol SOBuddyOutlineViewMouseDelegate <NSObject>
- (void)outlineView:(SOBuddyOutlineView *)arg1 mouseDownInRow:(long long)arg2;
- (void)outlineView:(SOBuddyOutlineView *)arg1 mouseUpInRow:(long long)arg2;
@end

