//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SocialUI/SOBuddyOutlineViewBaseRowView.h>

@class NSTextField;

@interface SOBuddyOutlineViewGroupView : SOBuddyOutlineViewBaseRowView
{
    NSTextField *_buddyCountLabel;
}

+ (id)highlightedAttributes;
+ (id)defaultAttributes;
@property(retain) NSTextField *buddyCountLabel; // @synthesize buddyCountLabel=_buddyCountLabel;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;

@end

