//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SocialUI/NSObject-Protocol.h>

@class NSView, SOTokenAttachmentCell;

@protocol SOTokenAttachmentCellDelegate <NSObject>
- (void)tokenAttachmentCell:(SOTokenAttachmentCell *)arg1 willBeDestroyedWithRepresentedObject:(id)arg2;
- (BOOL)tokenAttachmentCellShouldShowDedicingBackground:(SOTokenAttachmentCell *)arg1;
- (BOOL)tokenAttachmentCellHasErrorState:(SOTokenAttachmentCell *)arg1;
- (BOOL)tokenAttachmentCell:(SOTokenAttachmentCell *)arg1 doubleClickedInRect:(struct CGRect)arg2 ofView:(NSView *)arg3;
@end

