//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUICore/PXSectionedDataSource.h>

@interface PXAssetsDataSource : PXSectionedDataSource
{
}

- (id)startingAssetReference;
- (id)assetReferenceForAssetReference:(id)arg1;
- (struct PXSimpleIndexPath)indexPathForAssetReference:(id)arg1;
- (id)assetReferenceAtItemIndexPath:(struct PXSimpleIndexPath)arg1;
- (Class)objectReferenceClassForItem;
- (id)assetAtItemIndexPath:(struct PXSimpleIndexPath)arg1;
- (id)assetCollectionAtSectionIndexPath:(struct PXSimpleIndexPath)arg1;

@end

