//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IASUtilities/IASLocalSecretPrompt.h>

#import <AOSUI/IASLocalSecretDelegate-Protocol.h>

@class NSString;

@interface MMPromptForLocalSecret : IASLocalSecretPrompt <IASLocalSecretDelegate>
{
    long long _onceToken;
    NSString *_cachedFullUserName;
}

+ (void)getLocalSecretWithWindow:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
@property(copy) NSString *cachedFullUserName; // @synthesize cachedFullUserName=_cachedFullUserName;
@property long long onceToken; // @synthesize onceToken=_onceToken;
- (id)userFullName;
- (void)secretEntered:(id)arg1;
- (void)secretEntryCancelled;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

