//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AOSUI/NSObject-Protocol.h>

@protocol MMWebViewButtonBarDelegate <NSObject>

@optional
- (void)button3Pressed:(id)arg1;
- (void)button2Pressed:(id)arg1;
- (void)button1Pressed:(id)arg1;
@end

