//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString;

@interface UIMovieClosedCaptionData : NSObject
{
    NSString *_language;
    NSMutableArray *_data;
}

@property(retain, nonatomic) NSString *language; // @synthesize language=_language;
- (void).cxx_destruct;

@end

