//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface MUCGPDFWriter : NSObject
{
}

- (_Bool)writeCGPDFDocument:(struct CGPDFDocument *)arg1 toConsumer:(struct CGDataConsumer *)arg2 withAnnotationsFromController:(id)arg3 replacedAnnotationMaps:(id)arg4 encryptionPassword:(id)arg5 error:(id *)arg6 delegateBlock:(CDUnknownBlockType)arg7;

@end

