//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <StoreKit/SKPayment.h>

@class NSData, NSString;

@interface SKMutablePayment : SKPayment
{
}

@property(copy, nonatomic) NSString *applicationUsername; // @dynamic applicationUsername;
@property(copy, nonatomic) NSData *requestData; // @dynamic requestData;
@property(nonatomic) long long quantity; // @dynamic quantity;
@property(copy, nonatomic) NSString *productIdentifier; // @dynamic productIdentifier;

@end

