//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTabViewItem.h>

@interface PKUITabViewItem : NSTabViewItem
{
}

- (long long)_addToolTipRect:(struct CGRect)arg1;
- (struct CGSize)sizeOfLabel:(BOOL)arg1;
- (void)drawLabel:(BOOL)arg1 inRect:(struct CGRect)arg2;

@end

