//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AVFoundation/AVMediaSelectionOption.h>

@interface AVMediaSelectionOption (AVPlayerControllerInternal)
- (BOOL)_containsOnlyAC3;
- (BOOL)_containsAC3;
- (id)_extendedLanguageTagOrUndetermined;
- (long long)_caseInsensitiveCompare:(id)arg1;
@end

