//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableRowView.h>

@class SeparatorView;

__attribute__((visibility("hidden")))
@interface FormAutoFillCompletionControllerRowView : NSTableRowView
{
    SeparatorView *_separatorView;
}

- (void).cxx_destruct;
- (void)drawSelectionInRect:(struct CGRect)arg1;
@property(nonatomic) BOOL shouldDrawSeparator;

@end

