//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSMenu.h>

@interface NSMenu (TextEncodingSupport)
- (void)addStandardTextEncodingMenuItemsWithTarget:(id)arg1 action:(SEL)arg2 preferredEncoding:(unsigned int)arg3;
- (void)addItemToMenuForEncoding:(unsigned int)arg1 withTarget:(id)arg2 action:(SEL)arg3;
@end

