//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Safari/NSObject-Protocol.h>

@class RWIApplication, RWIDriver, RWITarget;

@protocol RWITargetDelegate <NSObject>

@optional
- (void)targetDidBecomeNotReady:(RWITarget *)arg1;
- (void)targetDidBecomeReady:(RWITarget *)arg1;
- (void)target:(RWITarget *)arg1 didRemoveDriver:(RWIDriver *)arg2;
- (void)target:(RWITarget *)arg1 didAddDriver:(RWIDriver *)arg2;
- (void)target:(RWITarget *)arg1 didRemoveApplication:(RWIApplication *)arg2;
- (void)target:(RWITarget *)arg1 didAddApplication:(RWIApplication *)arg2;
@end

