//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSPopUpButton.h>

@class NSTrackingArea;

__attribute__((visibility("hidden")))
@interface SafeAutoFillChoicesPopUpButton : NSPopUpButton
{
    NSTrackingArea *_trackingArea;
}

+ (Class)cellClass;
- (void).cxx_destruct;
- (id)accessibilityRole;
- (BOOL)isAccessibilityElement;
- (void)showButtonArrows;
- (void)removeButtonHighlight;
- (void)mouseExited:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)updateTrackingAreas;
- (id)popUpButtonCell;
@property(nonatomic) double menuWidth;
@property(nonatomic) double highlightOffset;
- (BOOL)allowsVibrancy;

@end

