//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class WebBookmarkList;

__attribute__((visibility("hidden")))
@interface TopLevelBookmarkHousekeeper : NSObject
{
    WebBookmarkList *_rootBookmark;
}

- (void).cxx_destruct;
- (void)_collectVisibleBookmarksBars:(id *)arg1 menus:(id *)arg2;
- (void)_getNumberOfVisibleDuplicateBookmarkBars:(unsigned long long *)arg1 menus:(unsigned long long *)arg2 visibleBookmarksBars:(id)arg3 visibleBookmarksMenus:(id)arg4;
- (void)_getNumberOfVisibleDuplicateBookmarkBars:(unsigned long long *)arg1 menus:(unsigned long long *)arg2;
- (void)_reportNumberOfUserVisibleDuplicateBookmarkBars:(unsigned long long)arg1 duplicateBookmarkMenus:(unsigned long long)arg2;
- (BOOL)mergeUserVisibleTopLevelDuplicates;
- (void)reportUserVisibleTopLevelDuplicates;
- (id)initWithRootBookmark:(id)arg1;
- (id)init;

@end

