//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSTimer;

__attribute__((visibility("hidden")))
@interface TrackingDataControllerObjCAdapter : NSObject
{
    struct TrackingDataController *_trackingDataController;
    NSTimer *_cookieUpdateCoalescingTimer;
}

- (void).cxx_destruct;
- (void)invalidateCookieUpdateCoalescingTimer;
- (void)refreshCookieUpdateCoalescingTimer;
- (void)_updateCookiesTimerFired:(id)arg1;
- (void)acceptCookiesPolicyChangedHandler:(id)arg1;
- (void)registerForBlockCookiesPolicyChangeNotifications;
- (void)dealloc;
- (id)initWithTrackingDataController:(struct TrackingDataController *)arg1;

@end

