//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TXRXCAssetParser : NSObject
{
}

+ (id)exportTexture:(id)arg1 toXCAssetWithName:(id)arg2 setAttributes:(id)arg3 textureConfigList:(id)arg4 location:(id)arg5 error:(id *)arg6;
+ (BOOL)exportMipmapSet:(id)arg1 face:(unsigned long long)arg2 directoryPath:(id)arg3 textureConfig:(id)arg4 error:(id *)arg5;

@end

