//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Metal/NSObject-Protocol.h>

@class NSArray, NSString;
@protocol MTLDevice;

@protocol MTLFunction <NSObject>
@property(readonly) NSString *name;
@property(readonly) NSArray *vertexAttributes;
@property(readonly) unsigned long long functionType;
@property(readonly) id <MTLDevice> device;
@end

