//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class CDPContext, CDPFollowUpContext, NSString;
@protocol CDPAuthProviderInternal, CDPStateUIProviderInternal;

@protocol CDPDaemonProtocol
- (void)postFollowUpWithContext:(CDPFollowUpContext *)arg1 completion:(void (^)(_Bool, NSError *))arg2;
- (void)clearFollowUpWithContext:(CDPFollowUpContext *)arg1 completion:(void (^)(_Bool, NSError *))arg2;
- (void)recoverIDMSRecoveryDictionaryWithContext:(CDPContext *)arg1 uiProvider:(id <CDPStateUIProviderInternal>)arg2 authProvider:(id <CDPAuthProviderInternal>)arg3 completion:(void (^)(NSDictionary *, NSError *))arg4;
- (void)preflightStingrayDisableForContext:(CDPContext *)arg1 uiProvider:(id <CDPStateUIProviderInternal>)arg2 completion:(void (^)(_Bool, NSError *))arg3;
- (void)getStingrayDisableEligibility:(CDPContext *)arg1 completion:(void (^)(_Bool, NSError *))arg2;
- (void)getStingrayStateForContext:(CDPContext *)arg1 completion:(void (^)(_Bool, NSError *))arg2;
- (void)setStingrayState:(_Bool)arg1 context:(CDPContext *)arg2 completion:(void (^)(_Bool, NSError *))arg3;
- (void)removeNonViewAwarePeersFromCircleWithContext:(CDPContext *)arg1 completion:(void (^)(_Bool, NSError *))arg2;
- (void)setUserVisibleKeychainSyncEnabled:(_Bool)arg1 withCompletion:(void (^)(_Bool, NSError *))arg2;
- (void)isUserVisibleKeychainSyncEnabledWithCompletion:(void (^)(_Bool))arg1;
- (void)hasLocalSecretWithCompletion:(void (^)(_Bool))arg1;
- (void)isICDPEnabledForDSID:(NSString *)arg1 checkWithServer:(_Bool)arg2 completion:(void (^)(_Bool))arg3;
- (void)finishOfflineLocalSecretChangeWithContext:(CDPContext *)arg1 uiProvider:(id <CDPStateUIProviderInternal>)arg2 completion:(void (^)(_Bool, NSError *))arg3;
- (void)localSecretChangedTo:(NSString *)arg1 secretType:(unsigned long long)arg2 context:(CDPContext *)arg3 completion:(void (^)(_Bool, NSError *))arg4;
- (void)shouldPerformRepairForContext:(CDPContext *)arg1 completion:(void (^)(_Bool, NSError *))arg2;
- (void)repairCloudDataProtectionStateWithContext:(CDPContext *)arg1 uiProvider:(id <CDPStateUIProviderInternal>)arg2 completion:(void (^)(_Bool, NSError *))arg3;
- (void)handleCloudDataProtectionStateWithContext:(CDPContext *)arg1 uiProvider:(id <CDPStateUIProviderInternal>)arg2 completion:(void (^)(_Bool, _Bool, NSError *))arg3;
@end

