//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, TLSound;

@interface TLAlertTone : NSObject
{
    NSString *_filePath;
    TLSound *_actualSound;
    TLSound *_previewSound;
}

@property(retain, nonatomic, setter=_setPreviewSound:) TLSound *previewSound; // @synthesize previewSound=_previewSound;
@property(retain, nonatomic, setter=_setActualSound:) TLSound *actualSound; // @synthesize actualSound=_actualSound;
@property(copy, nonatomic, setter=_setFilePath:) NSString *filePath; // @synthesize filePath=_filePath;
- (void)dealloc;
- (id)initWithFilePath:(id)arg1 actualSoundID:(unsigned int)arg2 previewSoundID:(unsigned int)arg3;

@end

