//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreData/_NSQueryGenerationToken.h>

#import <CoreData/NSCoding-Protocol.h>
#import <CoreData/NSSecureCoding-Protocol.h>

__attribute__((visibility("hidden")))
@interface _NSXPCQueryGenerationToken : _NSQueryGenerationToken <NSCoding, NSSecureCoding>
{
}

+ (BOOL)supportsSecureCoding;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

