//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (XSMergedAdminAction)
- (BOOL)isSimilarToDictionary:(id)arg1 ignoringKeys:(id)arg2;
- (id)appendBriefDescriptionWithIndentation:(unsigned long long)arg1 toString:(id)arg2;
@end

