//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HealthUI/NSObject-Protocol.h>

@class HKDataUnit, HKUnitController, NSNumber, NSString;

@protocol HKNumberFormatter <NSObject>
- (NSString *)stringFromNumber:(NSNumber *)arg1 dataUnit:(HKDataUnit *)arg2 unitController:(HKUnitController *)arg3;
- (_Bool)returnsUnitWithValueForDisplay;
@end

