//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ViewBridge/NSRemoteViewController.h>

#import <PhotosUI/NSRemoteViewDelegate-Protocol.h>

@class NSString;
@protocol PHEditingRemoteViewControllerDelegate;

@interface PHEditingRemoteViewController : NSRemoteViewController <NSRemoteViewDelegate>
{
    id <PHEditingRemoteViewControllerDelegate> _delegate;
    NSString *_serviceName;
    NSString *_serviceSubclassName;
}

@property(retain, nonatomic) NSString *serviceSubclassName; // @synthesize serviceSubclassName=_serviceSubclassName;
@property(retain, nonatomic) NSString *serviceName; // @synthesize serviceName=_serviceName;
@property(nonatomic) __weak id <PHEditingRemoteViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)serviceViewControllerInterface;
- (BOOL)view:(id)arg1 shouldResize:(struct CGSize)arg2;
- (void)viewServiceDidTerminateWithError:(id)arg1;
- (void)setupRemoteView;
- (void)awakeFromNib;
- (void)loadView;
- (id)initWithServiceName:(id)arg1 serviceSubclassName:(id)arg2;
- (id)remoteView;

// Remaining properties
@property(readonly) BOOL shouldRetainExportedObject;

@end

