//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProKit/NSProButtonCell.h>

__attribute__((visibility("hidden")))
@interface _NSProThemeWidgetCell : NSProButtonCell
{
    int _buttonID;
}

- (void)setObscured:(BOOL)arg1;
- (BOOL)isObscured;
- (void)setButtonID:(int)arg1;
- (void)accessibilityPerformAction:(id)arg1;
- (BOOL)accessibilityIsFocusedAttributeSettable;
- (id)accessibilityTitleAttribute;
- (BOOL)accessibilityIsSubroleAttributeSettable;
- (id)accessibilitySubroleAttribute;
- (id)accessibilityAttributeNames;

@end

