//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProKit/NSProSegmentedControl.h>

#import <ProKit/NSProPaneCapProtocol-Protocol.h>

@interface NSProPaneCapSegmentedControl : NSProSegmentedControl <NSProPaneCapProtocol>
{
    void *_paneCapReserved1;
    void *_paneCapReserved2;
    void *_paneCapReserved3;
}

+ (void)initialize;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_paneCapSetFont;
@property int paneCapTint; // @dynamic paneCapTint;
@property int paneCapStyle; // @dynamic paneCapStyle;

@end

