//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ProKit/NSProNamedSystemColor.h>

__attribute__((visibility("hidden")))
@interface NSProStandardSystemColor : NSProNamedSystemColor
{
    long long _tintIndex;
    long long _shadeIndex;
}

- (id)initStandardColorWithTint:(long long)arg1 shade:(long long)arg2;
- (void)resolveToConcreteColor;

@end

