//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (PrototypeTools_PhotosUICore)
+ (id)px_viewControllerWithContinuousOutputProducer:(CDUnknownBlockType)arg1;
+ (id)px_viewControllerWithAsynchronousOutputProducer:(CDUnknownBlockType)arg1;
+ (id)px_viewControllerWithOutput:(CDUnknownBlockType)arg1;
+ (id)px_viewControllerWithSettings:(id)arg1;
@end

