//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TVKit/__TVMusicDataClientResultsController.h>

@class TVSDataCollection;

@interface __TVMusicArtistsDataClientResultsController : __TVMusicDataClientResultsController
{
    TVSDataCollection *_genre;
}

- (void).cxx_destruct;
- (id)queryForController:(id)arg1;
- (id)initWithGenre:(id)arg1;

@end

