//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextField.h>

@interface _TVTextEntryTextField : UITextField
{
    _Bool _allowsFocus;
}

@property(nonatomic) _Bool allowsFocus; // @synthesize allowsFocus=_allowsFocus;
- (id)text;
- (_Bool)canBecomeFocused;
- (id)initWithFrame:(struct CGRect)arg1;

@end

