//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class SATVButton, SATVHeaderView, UIButton, UILabel, _SATVChoiceButtonContainerView;
@protocol SATVChoiceViewDataSource, SATVChoiceViewDelegate;

@interface SATVChoiceView : UIView
{
    SATVHeaderView *_headerView;
    id <SATVChoiceViewDataSource> _dataSource;
    id <SATVChoiceViewDelegate> _delegate;
    SATVButton *_choiceHeaderButton;
    SATVButton *_footerButton;
    UILabel *_footnoteLabel;
    _SATVChoiceButtonContainerView *_choiceButtonContainer;
    UIButton *_firstChoiceButton;
    UIButton *_secondChoiceButton;
}

@property(retain, nonatomic) UIButton *secondChoiceButton; // @synthesize secondChoiceButton=_secondChoiceButton;
@property(retain, nonatomic) UIButton *firstChoiceButton; // @synthesize firstChoiceButton=_firstChoiceButton;
@property(retain, nonatomic) _SATVChoiceButtonContainerView *choiceButtonContainer; // @synthesize choiceButtonContainer=_choiceButtonContainer;
@property(retain, nonatomic) UILabel *footnoteLabel; // @synthesize footnoteLabel=_footnoteLabel;
@property(retain, nonatomic) SATVButton *footerButton; // @synthesize footerButton=_footerButton;
@property(retain, nonatomic) SATVButton *choiceHeaderButton; // @synthesize choiceHeaderButton=_choiceHeaderButton;
@property(nonatomic) __weak id <SATVChoiceViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <SATVChoiceViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) SATVHeaderView *headerView; // @synthesize headerView=_headerView;
- (void).cxx_destruct;
- (void)_didSelectFooterButton;
- (void)_didSelectButton:(id)arg1;
- (id)_newFooterButton;
- (id)_newDefaultButton;
- (id)_choiceHeaderButton;
- (void)_populateView;
- (struct CGSize)_computeFramesForBounds:(struct CGRect)arg1 forCalculationOnly:(_Bool)arg2;
- (void)reloadData;
- (void)focusedViewDidChange;
- (_Bool)canBecomeFocused;
- (id)preferredFocusEnvironments;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

