//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SetupAssistantTV/SATVTableViewController.h>

#import <SetupAssistantTV/SATVTouchRemoteSetupManagerDelegate-Protocol.h>

@class NSString, UILabel;

@interface SATVTapToSetupController : SATVTableViewController <SATVTouchRemoteSetupManagerDelegate>
{
    UILabel *_footerLabel;
    NSString *_setupDeviceName;
    NSString *_setupNetworkName;
}

+ (_Bool)controllerNeedsToRun;
@property(copy, nonatomic) NSString *setupNetworkName; // @synthesize setupNetworkName=_setupNetworkName;
@property(copy, nonatomic) NSString *setupDeviceName; // @synthesize setupDeviceName=_setupDeviceName;
- (void).cxx_destruct;
- (void)_showFooterLabelHint;
- (void)_presentError:(id)arg1;
- (void)_restartTouchRemoteSetup;
- (void)_stopTouchRemoteSetup;
- (void)_startTouchRemoteSetup;
- (void)touchRemoteSetupManager:(id)arg1 presentErrorAlert:(id)arg2;
- (void)touchRemoteSetupManagerStartTimeoutExpired:(id)arg1;
- (void)touchRemoteSetupManager:(id)arg1 didFailSetupWithError:(id)arg2;
- (void)touchRemoteSetupManagerDidFinishSetup:(id)arg1;
- (void)touchRemoteSetupManager:(id)arg1 didFinishAuthenticationForAccount:(unsigned long long)arg2 withResult:(_Bool)arg3 error:(id)arg4;
- (void)touchRemoteSetupManager:(id)arg1 willAttemptAuthenticationForAccount:(unsigned long long)arg2;
- (void)touchRemoteSetupManager:(id)arg1 networkConnectionStateDidChange:(long long)arg2;
- (_Bool)touchRemoteSetupManager:(id)arg1 shouldConnectToNetworkWithName:(id)arg2;
- (void)touchRemoteSetupManager:(id)arg1 didBeginConfigurationPhase:(long long)arg2 withMetadata:(id)arg3;
- (void)touchRemoteSetupManager:(id)arg1 didBeginSetupWithDeviceName:(id)arg2;
- (void)touchRemoteSetupManagerDidPromptToBeginSetup:(id)arg1;
- (id)presentingControllerForSetupManager:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (void)didMoveToParentViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

