//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, SATVButton, UIFocusGuide, UILabel, UITextField;

@interface SATVLoginView : UIView
{
    _Bool _touchInputEnabled;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UITextField *_textField;
    SATVButton *_continueButton;
    SATVButton *_skipButton;
    SATVButton *_useSeparateIDsButton;
    UIView *_systemInputView;
    NSArray *_keyboardConstraints;
    UIFocusGuide *_gridFocusGuide;
}

@property(retain, nonatomic) UIFocusGuide *gridFocusGuide; // @synthesize gridFocusGuide=_gridFocusGuide;
@property(nonatomic) _Bool touchInputEnabled; // @synthesize touchInputEnabled=_touchInputEnabled;
@property(retain, nonatomic) NSArray *keyboardConstraints; // @synthesize keyboardConstraints=_keyboardConstraints;
@property(readonly, nonatomic) UIView *systemInputView; // @synthesize systemInputView=_systemInputView;
@property(readonly, nonatomic) SATVButton *useSeparateIDsButton; // @synthesize useSeparateIDsButton=_useSeparateIDsButton;
@property(readonly, nonatomic) SATVButton *skipButton; // @synthesize skipButton=_skipButton;
@property(readonly, nonatomic) SATVButton *continueButton; // @synthesize continueButton=_continueButton;
@property(readonly, nonatomic) UITextField *textField; // @synthesize textField=_textField;
@property(readonly, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)_setSystemInputView:(id)arg1;
- (void)_gridAlignFrame:(struct CGRect *)arg1;
- (void)focusedViewDidChange;
- (void)layoutSubviews;
- (void)updateConstraints;
@property(retain, nonatomic) UIView *preferredFocusedViewForGridLayoutGuide;
- (void)setSystemInputView:(id)arg1 touchInputEnabled:(_Bool)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

