//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SetupAssistantTV/NSObject-Protocol.h>

@class NSError, TVSDeviceActivationAction;

@protocol TVSDeviceActivationDelegate <NSObject>
- (void)activationAction:(TVSDeviceActivationAction *)arg1 didFailWithError:(NSError *)arg2;
- (void)activationActionDidSucceed:(TVSDeviceActivationAction *)arg1 successType:(unsigned long long)arg2;
@end

