//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface RDVersionMutator : NSObject
{
}

+ (void)clearOverridePlace:(id)arg1;
+ (void)mutateProxyState:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (id)newMutableVersion:(id)arg1;
+ (id)newMutableImageProxyState:(id)arg1;

@end

