//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class PDFPage, PDFView;
@protocol IOTiledPoolDelegate;

@interface TileRenderRequest : NSObject
{
    id <IOTiledPoolDelegate> target;
    PDFPage *page;
    PDFView *pdfView;
    struct CGRect tileFrame;
    double zoomFactor;
    struct CGAffineTransform matrix;
    _Bool shouldAntiAlias;
}

- (void).cxx_destruct;

@end

