//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIAlertView.h>

@interface CAMLowDiskSpaceAlertView : UIAlertView
{
}

+ (id)lowDiskAlertControllerWithTitle:(id)arg1 message:(id)arg2 settingsActionHandler:(CDUnknownBlockType)arg3;
+ (void)showUsageSettings;
- (id)initWithTitle:(id)arg1 message:(id)arg2 delegate:(id)arg3 cancelButtonTitle:(id)arg4 otherButtonTitles:(id)arg5;
- (id)initWithTitle:(id)arg1 message:(id)arg2 showSettingsButton:(_Bool)arg3 delegate:(id)arg4;

@end

