//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Notes/ICNFMCActivityTarget-Protocol.h>

@class NSArray, NSMutableSet, NSString;
@protocol ICNFMCActivityTarget;

@interface _ICNFMCActivityMonitorMultiTarget : NSObject <ICNFMCActivityTarget>
{
    NSMutableSet *_allTargets;
    id <ICNFMCActivityTarget> _primaryTarget;
}

@property(retain, nonatomic) id <ICNFMCActivityTarget> primaryTarget; // @synthesize primaryTarget=_primaryTarget;
- (void).cxx_destruct;
- (id)displayName;
@property(readonly, copy, nonatomic) NSArray *allTargets;
- (BOOL)removeActivityTarget:(id)arg1;
- (BOOL)addActivityTarget:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

