//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QTKit/NSObject-Protocol.h>

@class NSDictionary, NSString;

@protocol QTImageConsumer <NSObject>
- (void)flushImageBuffersAfterHostTime:(unsigned long long)arg1;
- (void)setImageBuffer:(struct __CVBuffer *)arg1 forHostTime:(unsigned long long)arg2;

@optional
- (NSString *)diagnosticString;
- (NSDictionary *)preferredAttributes;
@end

