//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QTKit/QTOpenGLTexture.h>

@class QTOpenGLTextureCacheTextureTile;

__attribute__((visibility("hidden")))
@interface QTOpenGLTextureCacheTexture : QTOpenGLTexture
{
    QTOpenGLTextureCacheTextureTile *_tile;
}

- (id)tilesInRect:(struct CGRect)arg1;
- (id)CIImageWithOptions:(id)arg1;
- (id)CIImage;
- (struct CGColorSpace *)colorSpace;
- (struct CGSize)size;
- (void)dealloc;
- (id)initWithOpenGLTextureCache:(id)arg1 imageBuffer:(struct __CVBuffer *)arg2;

@end

