//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <OfficeImport/PDAnimateBehavior.h>

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface PDAnimateEffectBehavior : PDAnimateBehavior
{
    BOOL mHasTransition;
    int mTransition;
    NSMutableDictionary *mPropertyMap;
}

@property(retain, nonatomic) NSMutableDictionary *propertyMap; // @synthesize propertyMap=mPropertyMap;
- (BOOL)hasProperties;
- (void)setTransition:(int)arg1;
- (int)transition;
- (BOOL)hasTransition;
- (void)dealloc;
- (id)init;

@end

