//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface WBListLevelOverride : NSObject
{
}

+ (void)write:(id)arg1 listLevelOverride:(id)arg2 wrdFormatOverride:(struct WrdListLevelFormatOverride *)arg3;
+ (void)readFrom:(id)arg1 listLevelOverride:(id)arg2 formatOverride:(struct WrdListLevelFormatOverride *)arg3 document:(id)arg4;

@end

