//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GameCenterPrivateUIMac/NSObject-Protocol.h>

@class GKGamePlayerDetailViewController, GKPlayer;

@protocol GKGamePlayerDetailViewControllerDelegate <NSObject>
- (void)gamePlayerDetailViewController:(GKGamePlayerDetailViewController *)arg1 showChallengeSuggestionsForPlayer:(GKPlayer *)arg2;
- (void)gamePlayerDetailViewController:(GKGamePlayerDetailViewController *)arg1 showInfoForPlayer:(GKPlayer *)arg2;
@end

