//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Automator/_AMiCalItem.h>

@class NSDate, NSString;

@interface _AMiCalOpenFileAlarm : _AMiCalItem
{
}

@property(copy) NSDate *triggerDate;
@property(copy) NSString *filepath;
@property long long triggerInterval;

@end

