//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Automator/AMAppleScriptAction.h>

@class AMApplicationDefinition;

@interface AMNewFindItemsAction : AMAppleScriptAction
{
    AMApplicationDefinition *_applicationDefinition;
}

@property(retain) AMApplicationDefinition *applicationDefinition; // @synthesize applicationDefinition=_applicationDefinition;
- (void)updateName;
- (void)updateNameForApplication:(id)arg1 findingName:(id)arg2;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithDefinition:(id)arg1 fromArchive:(BOOL)arg2;

@end

