//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <Home/NSCopying-Protocol.h>

@class HMCharacteristicMetadata, NSArray, NSMutableDictionary, NSSet;

@interface HFMultiStateValueSet : NSObject <NSCopying>
{
    HMCharacteristicMetadata *_characteristicMetadata;
    CDUnknownBlockType _valueComparator;
    NSMutableDictionary *_displayResultsByValue;
}

@property(readonly, nonatomic) NSMutableDictionary *displayResultsByValue; // @synthesize displayResultsByValue=_displayResultsByValue;
@property(copy, nonatomic) CDUnknownBlockType valueComparator; // @synthesize valueComparator=_valueComparator;
@property(readonly, nonatomic) HMCharacteristicMetadata *characteristicMetadata; // @synthesize characteristicMetadata=_characteristicMetadata;
- (void).cxx_destruct;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (void)removeValue:(id)arg1;
- (_Bool)addValue:(id)arg1 displayResults:(id)arg2;
- (id)displayResultsForValue:(id)arg1;
@property(readonly, nonatomic) NSArray *sortedValues;
@property(readonly, nonatomic) NSSet *allValues;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCharacteristicMetadata:(id)arg1;
- (id)init;

@end

