//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Home/HFStaticItemProvider.h>

@interface HFStatusItemProvider : HFStaticItemProvider
{
}

+ (id)_statusItemClasses;
- (id)initWithHome:(id)arg1 room:(id)arg2;
- (id)initWithHome:(id)arg1 items:(id)arg2;

@end

