//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Home/HFTimeConditionBuilder.h>

@class NSDateComponents, NSString;

@interface HFSunriseSunsetConditionBuilder : HFTimeConditionBuilder
{
    NSString *_significantEvent;
    NSDateComponents *_offset;
}

+ (_Bool)canHandlePredicate:(id)arg1;
@property(retain, nonatomic) NSDateComponents *offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSString *significantEvent; // @synthesize significantEvent=_significantEvent;
- (void).cxx_destruct;
- (void)_updatePredicate;
- (void)setComparisonType:(unsigned long long)arg1;
- (id)initWithExistingObject:(id)arg1 inHome:(id)arg2;

@end

