//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MediaPlayer/MPModelObject.h>

@class NSString;

@interface MPModelLyrics : MPModelObject
{
    _Bool _hasStoreLyrics;
    NSString *_text;
}

+ (id)__MPModelPropertyLyricsHasStoreLyrics__PROPERTY;
+ (id)__hasStoreLyrics__KEY;
+ (id)__MPModelPropertyLyricsText__PROPERTY;
+ (id)__text__KEY;
@property(nonatomic) _Bool hasStoreLyrics; // @synthesize hasStoreLyrics=_hasStoreLyrics;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
- (void).cxx_destruct;
- (id)descriptionWithType:(long long)arg1;

@end

