//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Photos/PHAdjustmentData.h>

@interface PHAdjustmentData (PUPhotoEditing)
- (long long)_pu_baseOrientationForAsset:(id)arg1;
- (_Bool)pu_loadPhotoEditModel:(id)arg1 forAsset:(id)arg2;
- (_Bool)pu_isPenultimateAvailable;
- (long long)pu_penultimateState;
- (long long)pu_adjustmentWorkVersion;
@end

