//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WebCore/DOMObject.h>

@interface DOMHTMLOptionsCollection : DOMObject
{
}

- (id)item:(unsigned int)arg1;
- (void)remove:(unsigned int)arg1;
- (void)add:(id)arg1 index:(unsigned int)arg2;
- (id)namedItem:(id)arg1;
@property unsigned int length;
@property int selectedIndex;
- (void)dealloc;

@end

