//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DifferentialPrivacy/_DPOBHSequenceMO.h>

@class NSString;

@interface _DPOBHFragmentMO : _DPOBHSequenceMO
{
}


// Remaining properties
@property(nonatomic) long long fragmentBitPosition; // @dynamic fragmentBitPosition;
@property(nonatomic) BOOL fragmentBitValue; // @dynamic fragmentBitValue;
@property(nonatomic) short fragmentPosition; // @dynamic fragmentPosition;
@property(nonatomic) short fragmentWidth; // @dynamic fragmentWidth;
@property(copy, nonatomic) NSString *plainFragment; // @dynamic plainFragment;
@end

