//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _DPStrings : NSObject
{
}

+ (id)unitTestRuntimeBlacklistDirectoryPath;
+ (id)unitTestSystemBlacklistDirectoryPath;
+ (id)unitTestReportsDirectoryPath:(id)arg1;
+ (id)unitTestDatabaseDirectoryPath:(id)arg1;
+ (id)unitTestOutputDirectoryPath;
+ (id)unitTestInputDirectoryPath;
+ (id)runtimeBlacklistDirectoryPath;
+ (id)systemBlacklistDirectoryPath;
+ (id)errorDomain;
+ (id)defaultBudgetKey;
+ (id)algorithmParametersPath;
+ (id)budgetPropertiesPath;
+ (id)keyPropertiesPath;
+ (id)keyNamesPath;
+ (id)reportsDirectoryPath;
+ (id)databaseDirectoryPath;
+ (id)machServiceName;

@end

