//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableSet.h>

@interface NSMutableSet (_DASAdditions)
- (void)_DAS_addOrReplaceObjectsFromArray:(id)arg1;
- (void)_DAS_unionSetOverridingExisting:(id)arg1;
- (void)_DAS_addOrReplaceObject:(id)arg1;
@end

