//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIWindow.h>

__attribute__((visibility("hidden")))
@interface UIClassicWindow : UIWindow
{
    _Bool _scaleForiPads;
}

@property(nonatomic) _Bool scaleForiPads; // @synthesize scaleForiPads=_scaleForiPads;
- (double)_adjustedWindowLevelFromLevel:(double)arg1;
- (_Bool)_shouldZoom;
- (_Bool)_isConstrainedByScreenJail;
- (struct CGRect)_sceneReferenceBounds;
- (void)_updateTransformLayerForClassicPresentation;

@end

