//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/NSObject-Protocol.h>

@class NSArray;

@protocol UIPreviewInteractionAnimating <NSObject>
@property(readonly, nonatomic, getter=isStopped) _Bool stopped;
@property(copy, nonatomic) NSArray *containerViews;
- (void)stopAnimations;
- (void)setAnimationsForCancel:(void (^)(void))arg1 completion:(void (^)(_Bool))arg2;
- (void)setAnimationsForCommit:(void (^)(void))arg1 completion:(void (^)(_Bool))arg2;
- (void)setAnimationsForPreview:(void (^)(void))arg1 completion:(void (^)(_Bool))arg2;
- (void)setAnimationsForInteractiveHighlight:(void (^)(void))arg1 completion:(void (^)(_Bool))arg2;
@end

