//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface TPFootnotePropertyStrings : NSObject
{
}

+ (id)stringForFootnoteNumbering:(int)arg1;
+ (id)stringForFootnoteFormat:(int)arg1;
+ (id)stringForFootnoteKind:(int)arg1;
+ (id)titleForFootnoteNumbering;
+ (id)titleForFootnoteFormat;
+ (id)titleForFootnoteKind;
+ (id)insertStringForFootnoteKind:(int)arg1;

@end

