//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface TSPUnknownContent : NSObject
{
    NSArray *_messages;
    NSArray *_ignoreAndPreserveFields;
    NSArray *_ignoreAndDropFields;
    NSArray *_savedIgnoreAndPreserveFields;
    NSArray *_savedIgnoreAndDropFields;
}

@property(readonly, nonatomic) NSArray *messages; // @synthesize messages=_messages;
- (void).cxx_destruct;
- (void)willModifyObject;
- (void)updateMessageInfo:(struct MessageInfo *)arg1;
- (void)saveToArchiver:(id)arg1;
- (void)loadFromUnarchiver:(id)arg1;
- (id)initWithMessages:(id)arg1 ignoreAndPreserveFields:(id)arg2 ignoreAndDropFields:(id)arg3;
- (id)init;

@end

