//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <iWorkImport/NSObject-Protocol.h>

@class TSUColor, TSULocale, TSWPLayoutManager, TSWPLayoutMetricsCache, TSWPStorage;
@protocol TSWPStyleProvider, TSWPTextWrap;

@protocol TSWPLayoutOwner <NSObject>
- (id <TSWPTextWrap>)textWrapper;
- (void)didLayoutChangingDirtyRanges;
- (void)layoutManager:(TSWPLayoutManager *)arg1 didClearDirtyRangeWithDelta:(long long)arg2 afterCharIndex:(unsigned long long)arg3;
- (void)layoutManagerNeedsLayout:(TSWPLayoutManager *)arg1;
- (_Bool)caresAboutStorageChanges;

@optional
- (TSWPLayoutMetricsCache *)metricsCacheForStorage:(TSWPStorage *)arg1;
- (void)didLayoutWithLayoutManager:(TSWPLayoutManager *)arg1;
- (TSUColor *)textColorOverride;
- (TSULocale *)locale;
- (_Bool)forceWesternLineBreaking;
- (id <TSWPStyleProvider>)styleProvider;
@end

