//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

__attribute__((visibility("hidden")))
@interface _NSCornerView : NSView
{
}

- (BOOL)_drawingEndSeparator;
- (id)_vibrancyFilter;
- (BOOL)allowsVibrancy;
- (void)drawRect:(struct CGRect)arg1;
- (struct CGRect)fillRect;
- (id)enclosingScrollView;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

