//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class _NSGestureRecognizerTransformAnalyzer;

__attribute__((visibility("hidden")))
@interface _NSMagnificationGestureRecognizerTouchAuxiliary : NSObject
{
    id _touchID1;
    id _touchID2;
    double _initialTouchDistance;
    _NSGestureRecognizerTransformAnalyzer *_transformAnalyzer;
}

- (void)dealloc;
- (id)init;

@end

