//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSAppearance;

__attribute__((visibility("hidden")))
@interface _NSPopoverPrivateData : NSObject
{
    long long closeReason;
    NSAppearance *customAppearance;
    CDStruct_4a40d4f7 _flags;
}

- (void)dealloc;

@end

