//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _NSPboardTypeConverter : NSObject
{
}

+ (void)pasteboard:(id)arg1 provideDataForType:(id)arg2;
+ (id)dataForType:(id)arg1 fromPasteboard:(id)arg2;

@end

