//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSCGSWindowLayerSurface, NSView, NSWindow;

__attribute__((visibility("hidden")))
@interface _NSViewLayerSurface : NSObject
{
    NSView *_view;
    NSWindow *_danglingWindow;
    NSWindow *_weakWindow;
    NSCGSWindowLayerSurface *_surface;
}

+ (id)_windowTitlebarLayerSurfaceForView:(id)arg1;
+ (void)initialize;
- (void)dealloc;
- (void)invalidate;
- (void)update;
- (id)initWithView:(id)arg1;

@end

