//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSColorSpaceSliders.h>

@class NSColor;

@interface NSHSBSliders : NSColorSpaceSliders
{
    id hueSlider;
    id saturationSlider;
    id brightnessSlider;
    id hueText;
    id saturationText;
    id brightnessText;
    id hsbView;
    NSColor *currColor;
    NSColor *backgroundColor;
    id sliderMatrix;
}

+ (id)genericColorSpace;
- (void)_adjustControls:(id)arg1 andSetColor:(BOOL)arg2;
- (void)adjustControls:(id)arg1;
- (BOOL)worksWhenModal;
- (void)viewSizeChanged:(id)arg1;
- (struct CGSize)requiredMinSize;
- (id)regularColorIfPossible:(id)arg1;
- (void)setMatchedColor:(id)arg1;
- (id)fieldEditableControl;
- (id)provideNewSubview:(id)arg1;

@end

