//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTouchBarPressAndHoldTransposer.h>

@class NSView;

@interface NSTouchBarStandardPopoverTransposer : NSTouchBarPressAndHoldTransposer
{
    struct CGRect _srcFrame;
    struct CGRect _dstFrame;
    NSView *_contentView;
    NSView *_hitView;
}

- (void)transposeTouch:(id)arg1;
- (struct CGPoint)tranposePoint:(struct CGPoint)arg1;
- (id)transposedTouchFromTouch:(id)arg1 toLocation:(struct CGPoint)arg2 prevLocation:(struct CGPoint)arg3 phase:(unsigned long long)arg4 view:(id)arg5;
- (void)dealloc;
- (id)initWithSourceFrame:(struct CGRect)arg1 destinationContentView:(id)arg2 frame:(struct CGRect)arg3;

@end

