//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppKit/_NSTouchBarItemLayoutWrapper-Protocol.h>

@class NSString;

@interface NSTouchBarLayoutItem : NSObject <_NSTouchBarItemLayoutWrapper>
{
    struct CGSize _minSize;
    struct CGSize _maxSize;
    BOOL _isSpace;
    float _visibilityPriority;
}

- (float)visibilityPriority;
@property(readonly) BOOL isSpace;
@property(readonly) struct CGSize maxSize;
@property(readonly) struct CGSize minSize;
- (id)initWithTouchBarItem:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly) struct CGSize contentClippingSize;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) double itemPadding;
@property(readonly) unsigned long long itemPosition;
@property(readonly) struct CGSize preferredSize;
@property(readonly) long long priorityIndex;
@property(readonly) Class superclass;

@end

