//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSViewController.h>

@class NSTouchBarItem, NSView;

__attribute__((visibility("hidden")))
@interface NSTouchBarEscapeKeyViewController : NSViewController
{
    NSTouchBarItem *_touchBarItem;
    NSView *_currentItemView;
}

- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)dealloc;
- (void)_noteTouchBarItemChanged;
@property(retain) NSTouchBarItem *touchBarItem;
- (void)loadView;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

