//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ScreenSaver/ScreenSaverImagesModule.h>

#import <ScreenSaver/NSCopying-Protocol.h>

@class NSURL;

@interface ScreenSaverRSSFeedModule : ScreenSaverImagesModule <NSCopying>
{
    NSURL *_feedURL;
}

+ (id)rssFeedModuleFromSubscription:(id)arg1;
+ (id)rssFeedModuleWithTitle:(id)arg1 url:(id)arg2;
- (BOOL)requiresGraphicsAcceleration;
- (id)initWithDictionary:(id)arg1;
- (id)dictionaryRepresentation;
- (BOOL)isSlideshow;
- (void)setFeedURL:(id)arg1;
- (id)feedURL;
- (id)path;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;

@end

