//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <NetworkServiceProxy/NSSecureCoding-Protocol.h>

@class NSDate, NSString;

@interface NPNetworkInfo : NSObject <NSSecureCoding>
{
    NSDate *_lastVisited;
    NSDate *_lastUsed;
}

+ (BOOL)supportsSecureCoding;
@property(retain) NSDate *lastUsed; // @synthesize lastUsed=_lastUsed;
@property(retain) NSDate *lastVisited; // @synthesize lastVisited=_lastVisited;
- (void).cxx_destruct;
@property(readonly) NSString *lastUsedDesc;
@property(readonly) NSString *lastVisitedDesc;
- (long long)compareLastVisited:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

