//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FULabel;

__attribute__((visibility("hidden")))
@interface FUErrorView : UIView
{
    FULabel *_errorLabel;
}

@property(retain) FULabel *errorLabel; // @synthesize errorLabel=_errorLabel;
- (void).cxx_destruct;
- (id)init;

@end

