//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface WBSJavaScriptDialogManager : NSObject
{
    NSMutableDictionary *_completionHandlers;
}

- (void).cxx_destruct;
- (void)dismissDialogForWebPIDIfNeeded:(int)arg1;
- (void)dismissPromptDialogForWebPID:(int)arg1 withResponse:(id)arg2;
- (void)dismissConfirmDialogForWebPID:(int)arg1 withResponse:(long long)arg2;
- (void)dismissAlertDialogForWebPID:(int)arg1;
- (id)unregisterDialogForWebPID:(int)arg1;
- (void)registerDialogForWebPID:(int)arg1 withCompletionHandler:(id)arg2;
- (id)init;

@end

