//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface VCWeakObjectHolder : NSObject
{
    id _weakObject;
}

+ (id)weakObjectHolderWithObject:(id)arg1;
@property(readonly, nonatomic) id strong;
- (void)dealloc;
- (id)initWithObject:(id)arg1;
- (id)init;

@end

