//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GeoServices/GEOComposedWaypoint.h>

@interface GEOComposedWaypoint (MNExtras)
- (id)navSpokenAnnouncementAtArrival:(_Bool)arg1;
- (id)navSpokenAnnouncementAtStartForTransportType:(int)arg1;
- (id)navAnnouncementAddress;
- (id)navAnnouncementNameWithSpecialContacts:(_Bool)arg1;
- (id)localeIdentifier;
- (id)navDisplayNameWithSpecialContacts:(_Bool)arg1;
- (id)navDisplayName;
- (id)navDisplayAddress;
@property(readonly, nonatomic) int destinationType;
@end

