//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MarkupUI/NSObject-Protocol.h>

@protocol AKUserInterfaceItem <NSObject>
- (long long)tag;

@optional
- (long long)tagForSegment:(long long)arg1;
@end

