//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <CoreCDP/NSSecureCoding-Protocol.h>

@class NSString;

@interface CDPFollowUpContext : NSObject <NSSecureCoding>
{
    BOOL _shouldNotify;
    BOOL _force;
    NSString *_followUpType;
}

+ (BOOL)supportsSecureCoding;
+ (id)contextForOfflinePasscodeChange;
+ (id)contextForStateRepair;
+ (id)contextWithType:(id)arg1;
@property(copy, nonatomic) NSString *followUpType; // @synthesize followUpType=_followUpType;
@property(nonatomic) BOOL force; // @synthesize force=_force;
@property(nonatomic) BOOL shouldNotify; // @synthesize shouldNotify=_shouldNotify;
- (void).cxx_destruct;
- (id)description;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

