//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface PKDiagnostics : NSObject
{
}

+ (id)_metadataForCardAtURL:(id)arg1;
+ (id)_allPasses;
+ (id)_secureElementData;
+ (id)generateUbiquityDiagnosticsFile:(BOOL)arg1;
+ (void)generateZippedDiagnosticsPackageWithPassLibrary:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
+ (void)generateDiagnosticsPackageWithPassLibrary:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;

@end

