//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol NFSession, OS_dispatch_queue;

@interface PKPaymentSessionHandle : NSObject
{
    NSObject<OS_dispatch_queue> *_internalSessionSerialQueue;
    id <NFSession> _sessionHandle;
}

+ (id)paymentSessionHandleWithInternalSessionHandle:(id)arg1;
- (void).cxx_destruct;
- (void)invalidateSession;
- (BOOL)isFirstInQueue;
- (id)initWithInternalSessionHandle:(id)arg1;

@end

