//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSView.h>

@class NSButton;

@interface _NSTitlebarRenamingButtonHolderContentView : NSView
{
    NSButton *_button;
}

@property NSButton *button; // @synthesize button=_button;
- (BOOL)_buttonRolloverDisabled;
- (struct CGRect)_clickableButtonRect;

@end

