//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import <MessageUI/MFModernAddressAtomDelegate-Protocol.h>
#import <MessageUI/MFPassthroughViewProvider-Protocol.h>

@class NSArray, NSDictionary, NSMutableArray, NSString, UIColor, UILabel;
@protocol MFModernLabelledAtomListDelegate;

@interface MFModernLabelledAtomList : UIView <MFPassthroughViewProvider, MFModernAddressAtomDelegate>
{
    UILabel *_label;
    void *_addressBook;
    id <MFModernLabelledAtomListDelegate> _delegate;
    NSArray *_addresses;
    NSMutableArray *_addressAtoms;
    NSString *_title;
    UIColor *_labelTextColor;
    NSDictionary *_recipients;
    _Bool _labelVisible;
    unsigned int _needsReflow:1;
    double _previousWidth;
    UILabel *_lastBaselineDeceptionLabel;
    _Bool _primary;
    unsigned long long _numberOfRows;
    double _lineSpacing;
    NSArray *_viewsToDodge;
}

+ (double)spaceBetweenColonAndFirstAtomNaturalEdge;
+ (double)atomLineHeight;
+ (id)primaryLabelFont;
+ (id)defaultLabelFont;
+ (id)defaultLabelTextColor;
@property(retain, nonatomic) NSArray *viewsToDodge; // @synthesize viewsToDodge=_viewsToDodge;
@property(nonatomic) double lineSpacing; // @synthesize lineSpacing=_lineSpacing;
@property(nonatomic, getter=isPrimary) _Bool primary; // @synthesize primary=_primary;
@property(readonly, nonatomic) unsigned long long numberOfRows; // @synthesize numberOfRows=_numberOfRows;
@property(retain, nonatomic) UIColor *labelTextColor; // @synthesize labelTextColor=_labelTextColor;
@property(readonly, nonatomic) UILabel *label; // @synthesize label=_label;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (struct CGPoint)baselinePointForRow:(unsigned long long)arg1;
- (void)setOverrideFont:(id)arg1;
- (id)viewForLastBaselineLayout;
- (id)viewForFirstBaselineLayout;
- (void)crossFadeLabelVisibility:(_Bool)arg1 atomSeparatorStyle:(int)arg2 withAnimationCoordinator:(id)arg3;
- (id)passthroughViews;
- (void)setOpaque:(_Bool)arg1;
- (void)setAtomAlpha:(double)arg1;
- (id)addressAtoms;
- (id)atomDisplayStrings;
- (id)title;
- (void)updateAtomsForVIP;
@property(nonatomic, getter=isLabelVisible) _Bool labelVisible;
- (struct CGRect)labelFrame;
- (id)labelText;
- (void)setAddressAtomsArePrimary:(_Bool)arg1;
- (void)setAddressAtomSeparatorStyle:(int)arg1;
- (void)setAddressAtomScale:(double)arg1;
- (void)setAddressAtomTarget:(id)arg1 action:(SEL)arg2;
- (double)_remainingSpaceForRowAtPoint:(struct CGPoint)arg1;
- (struct CGRect)_frameForAtomAtIndex:(unsigned long long)arg1 withStartingPoint:(struct CGPoint)arg2 row:(inout unsigned long long *)arg3;
- (void)_reflow;
- (void)_setNeedsReflow;
- (void)enumerateAddressAtomsUsingBlock:(CDUnknownBlockType)arg1;
- (void)addressAtom:(id)arg1 displayStringDidChange:(id)arg2;
- (void)setDelegate:(id)arg1;
- (void)_reflowIfNeeded;
- (void)layoutSubviews;
- (void)addressBookDidChange:(id)arg1;
- (void)dealloc;
- (struct CGSize)intrinsicContentSize;
- (void)setAddresses:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (id)initWithLabel:(id)arg1 title:(id)arg2 addressBook:(void *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

