//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MediaRemote/MRDeviceInfo.h>

@class NSString;

@interface MRMutableDeviceInfo : MRDeviceInfo
{
}

@property(nonatomic, getter=isPairingAllowed) BOOL pairingAllowed; // @dynamic pairingAllowed;
@property(nonatomic) unsigned long long protocolVersion; // @dynamic protocolVersion;
@property(copy, nonatomic) NSString *applicationBundleVersion; // @dynamic applicationBundleVersion;
@property(copy, nonatomic) NSString *applicationBundleIdentifier; // @dynamic applicationBundleIdentifier;
@property(copy, nonatomic) NSString *systemBuildVersion; // @dynamic systemBuildVersion;
@property(copy, nonatomic) NSString *localizedModelName; // @dynamic localizedModelName;
@property(copy, nonatomic) NSString *name; // @dynamic name;
@property(copy, nonatomic) NSString *uniqueIdentifier; // @dynamic uniqueIdentifier;

@end

