//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSDate, TVSSecureKeyRequest;

@interface TVSSecureKeyResponse : NSObject
{
    NSData *_keyData;
    NSDate *_renewalDate;
    TVSSecureKeyRequest *_request;
}

@property(retain, nonatomic) TVSSecureKeyRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) NSDate *renewalDate; // @synthesize renewalDate=_renewalDate;
@property(retain, nonatomic) NSData *keyData; // @synthesize keyData=_keyData;
- (void).cxx_destruct;

@end

