//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TVServices/TVSURLMediaItem.h>

#import <TVServices/TVSSecureKeyDeliveryCoordinatorDelegate-Protocol.h>

@class NSError, TVSMutableBookmark, TVSPlayer, TVSSecureKeyDeliveryCoordinator;

@interface TVSStoreAuxiliaryMediaItem : TVSURLMediaItem <TVSSecureKeyDeliveryCoordinatorDelegate>
{
    TVSSecureKeyDeliveryCoordinator *_secureKeyDeliveryCoordinator;
    TVSMutableBookmark *_bookmark;
    NSError *_skdError;
    TVSPlayer *_scrubPlayer;
}

@property(retain, nonatomic) TVSPlayer *scrubPlayer; // @synthesize scrubPlayer=_scrubPlayer;
@property(retain, nonatomic) NSError *skdError; // @synthesize skdError=_skdError;
@property(retain, nonatomic) TVSMutableBookmark *bookmark; // @synthesize bookmark=_bookmark;
- (void).cxx_destruct;
- (void)_scrubPlayerItemDidLoad:(id)arg1;
- (id)replacementErrorForPlaybackError:(id)arg1;
- (void)secureKeyDeliveryCoordinator:(id)arg1 willFailWithError:(id)arg2;
- (void)secureKeyDeliveryCoordinatorWillSucceed:(id)arg1;
- (void)loadStreamingKeyForRequest:(id)arg1;
- (void)cleanUpMediaItem;
- (void)prepareForLoadingWithCompletion:(CDUnknownBlockType)arg1;
- (void)setMediaItemMetadata:(id)arg1 forProperty:(id)arg2;
- (id)mediaItemMetadataForProperty:(id)arg1;
- (void)dealloc;
- (id)initWithURL:(id)arg1 isHLS:(_Bool)arg2 disableMetadataMenu:(_Bool)arg3 bookmarkID:(id)arg4;
- (id)initWithURL:(id)arg1 traits:(id)arg2;

@end

