//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AudioVideoBridging/AVB17221AEMStandardStreamFormat.h>

@interface AVB17221AEM61883StreamFormat : AVB17221AEMStandardStreamFormat
{
}

+ (id)keyPathsForValuesAffectingFmt;
@property(readonly) unsigned char fmt; // @dynamic fmt;
- (void)setFmt:(unsigned char)arg1;
- (id)init;

@end

