//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface SCRPriority : NSObject
{
    long long _priority;
    id _representedObject;
}

@property(retain, nonatomic) id representedObject; // @synthesize representedObject=_representedObject;
@property(nonatomic) long long priority; // @synthesize priority=_priority;
- (long long)compare:(id)arg1;
- (void)dealloc;
- (id)initWithRepresentedObject:(id)arg1 priority:(long long)arg2;

@end

