//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SiriCoreDESPreferences : NSObject
{
}

+ (id)sharedPreferences;
- (void)synchronize;
- (void)setDESPolicyCDNOverride:(id)arg1;
- (id)DESPolicyCDNOverride;
- (void)setDESLotteryWinOverrideIsEnabled:(BOOL)arg1;
- (BOOL)DESLotteryWinOverrideIsEnabled;
- (void)setDESRecordingIsEnabled:(BOOL)arg1;
- (BOOL)DESRecordingIsEnabled;
- (void)setDESRecognitionIsEnabled:(BOOL)arg1;
- (BOOL)DESRecognitionIsEnabled;

@end

