//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class AUAudioUnitBusArray, AUAudioUnitPreset, AUParameterTree, NSArray, NSDictionary, NSString;

@interface AUAudioUnit : NSObject
{
    struct OpaqueAudioComponent *_component;
    NSString *_componentName;
    unsigned int _componentVersion;
    struct NSViewController *_cachedViewController;
    BOOL _renderResourcesAllocated;
    BOOL _allParameterValues;
    BOOL _shouldBypassEffect;
    BOOL _canProcessInPlace;
    BOOL _renderingOffline;
    unsigned int _maximumFramesToRender;
    long long _virtualMIDICableCount;
    NSArray *_factoryPresets;
    AUAudioUnitPreset *_currentPreset;
    double _latency;
    double _tailTime;
    long long _renderQuality;
    CDUnknownBlockType _musicalContextBlock;
    CDUnknownBlockType _transportStateBlock;
    NSString *_contextName;
    struct AudioComponentDescription _componentDescription;
    struct RealtimeState _realtimeState;
}

+ (id)keyPathsForValuesAffectingAllParameterValues;
+ (id)auAudioUnitForAudioUnit:(struct ComponentInstanceRecord *)arg1;
+ (void)instantiateWithComponentDescription:(struct AudioComponentDescription)arg1 options:(unsigned int)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (void)registerSubclass:(Class)arg1 asComponentDescription:(struct AudioComponentDescription)arg2 name:(id)arg3 version:(unsigned int)arg4;
@property(nonatomic) struct RealtimeState realtimeState; // @synthesize realtimeState=_realtimeState;
@property(copy) NSString *contextName; // @synthesize contextName=_contextName;
@property(copy) CDUnknownBlockType transportStateBlock; // @synthesize transportStateBlock=_transportStateBlock;
@property(copy) CDUnknownBlockType musicalContextBlock; // @synthesize musicalContextBlock=_musicalContextBlock;
@property(getter=isRenderingOffline) BOOL renderingOffline; // @synthesize renderingOffline=_renderingOffline;
@property(readonly) BOOL canProcessInPlace; // @synthesize canProcessInPlace=_canProcessInPlace;
@property BOOL shouldBypassEffect; // @synthesize shouldBypassEffect=_shouldBypassEffect;
@property long long renderQuality; // @synthesize renderQuality=_renderQuality;
@property(readonly) double tailTime; // @synthesize tailTime=_tailTime;
@property(readonly) double latency; // @synthesize latency=_latency;
@property(retain) AUAudioUnitPreset *currentPreset; // @synthesize currentPreset=_currentPreset;
@property(readonly, copy) NSArray *factoryPresets; // @synthesize factoryPresets=_factoryPresets;
@property(readonly) long long virtualMIDICableCount; // @synthesize virtualMIDICableCount=_virtualMIDICableCount;
@property(readonly) BOOL allParameterValues; // @synthesize allParameterValues=_allParameterValues;
@property unsigned int maximumFramesToRender; // @synthesize maximumFramesToRender=_maximumFramesToRender;
@property(readonly) BOOL renderResourcesAllocated; // @synthesize renderResourcesAllocated=_renderResourcesAllocated;
@property(readonly) struct AudioComponentDescription componentDescription; // @synthesize componentDescription=_componentDescription;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setRenderResourcesAllocated:(BOOL)arg1;
- (BOOL)shouldChangeToFormat:(id)arg1 forBus:(id)arg2;
- (void)requestViewControllerWithCompletionHandler:(CDUnknownBlockType)arg1;
- (void)setCachedViewController:(struct NSViewController *)arg1;
- (struct NSViewController *)cachedViewController;
@property(copy) NSDictionary *fullStateForDocument;
@property(copy) NSDictionary *fullState;
@property(readonly) AUAudioUnitBusArray *outputBusses;
@property(readonly) AUAudioUnitBusArray *inputBusses;
@property(readonly, copy) NSArray *channelCapabilities;
- (void)reset;
- (id)parametersForOverviewWithCount:(long long)arg1;
@property(readonly) AUParameterTree *parameterTree;
- (void)deallocateRenderResources;
- (BOOL)allocateRenderResourcesAndReturnError:(id *)arg1;
- (void)removeRenderObserver:(CDUnknownFunctionPointerType)arg1 userData:(void *)arg2;
- (void)addRenderObserver:(CDUnknownFunctionPointerType)arg1 userData:(void *)arg2;
- (void)removeRenderObserver:(long long)arg1;
- (long long)tokenByAddingRenderObserver:(CDUnknownBlockType)arg1;
@property(readonly) CDUnknownBlockType scheduleMIDIEventBlock;
@property(readonly, getter=isMusicDeviceOrEffect) BOOL musicDeviceOrEffect;
@property(readonly) CDUnknownBlockType scheduleParameterBlock;
- (CDUnknownBlockType)internalRenderBlock;
@property(readonly) CDUnknownBlockType renderBlock;
- (struct AUEventSchedule *)eventSchedule;
@property(readonly) unsigned int componentVersion;
@property(readonly, copy) NSString *manufacturerName;
@property(readonly, copy) NSString *audioUnitName;
@property(readonly, copy) NSString *componentName;
@property(readonly) struct OpaqueAudioComponent *component;
- (void)dealloc;
- (id)initWithComponentDescription:(struct AudioComponentDescription)arg1 error:(id *)arg2;
- (id)initWithComponentDescription:(struct AudioComponentDescription)arg1 options:(unsigned int)arg2 error:(id *)arg3;
- (id)init;

@end

