//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSMutableSet;

@interface MusicGenreResourceImagesCatalog : NSObject
{
    NSDictionary *_genreMappings;
    NSMutableSet *_unknownGenres;
}

+ (id)sharedGenreResourceImagesCatalog;
- (void).cxx_destruct;
- (id)_baseNameOfImageForGenreNamed:(id)arg1;
- (id)resourceURLForGenreNamed:(id)arg1;
- (void)registerGenreResouceImages;
- (id)nameOfImageForGenreNamed:(id)arg1;
- (id)init;

@end

