//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ToneKit/TKPickerItem.h>

@class NSString;

@interface TKPickerSectionItem : TKPickerItem
{
    NSString *_text;
}

@property(copy, nonatomic, setter=_setText:) NSString *text; // @synthesize text=_text;
- (void)_appendDescriptionOfAttributesToString:(id)arg1;
- (void)dealloc;

@end

