//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <LocalAuthenticationUI/LAUIDelegate-Protocol.h>

@class LAUIAuthenticationViewController;

@interface LAUIAuthenticationViewControllerUIDelegate : NSObject <LAUIDelegate>
{
    LAUIAuthenticationViewController *_viewController;
}

@property(nonatomic) __weak LAUIAuthenticationViewController *viewController; // @synthesize viewController=_viewController;
- (void).cxx_destruct;
- (void)event:(long long)arg1 params:(id)arg2 reply:(CDUnknownBlockType)arg3;
- (id)initWithViewController:(id)arg1;

@end

