//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NotesShared/ICAnalyticsReporterBase.h>

@interface ICUsageAnalyticsReporter : ICAnalyticsReporterBase
{
}

+ (void)clearSharedCollector;
+ (id)sharedReporter;
- (void)logChecklistLengthFromTrackedToDoParagraphs:(id)arg1;
- (void)incrementCountForKey:(id)arg1 withSignature:(id)arg2;
- (void)incrementCountForKey:(id)arg1;

@end

