//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSAttributedString.h>

@interface NSAttributedString (NSAttributedStringPersistenceAdditions)
+ (id)TT_attributedStringWithData:(id)arg1 createNewAttachmentsInNote:(id)arg2 error:(id *)arg3;
+ (id)TT_attributedStringWithArchive:(const struct String *)arg1 createNewAttachmentsInNote:(id)arg2 error:(id *)arg3;
- (BOOL)TT_isCopyableSize;
- (unsigned long long)TT_approximateAttachmentsSizeIncludingPreviews:(BOOL)arg1;
- (id)TT_serializeWithFlags:(unsigned long long)arg1 managedObjectContext:(id)arg2;
- (void)TT_saveToArchive:(struct String *)arg1 flags:(unsigned long long)arg2 managedObjectContext:(id)arg3;
@end

