//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WebKit/WKWebView.h>

@interface WKWebView (IC)
- (struct NSImage *)compassImageForColor:(struct NSColor *)arg1;
- (char *)createRGBAPixelBufferFromImage:(struct CGImage *)arg1;
- (struct NSColor *)keyColorFromImage:(struct NSImage *)arg1;
- (struct NSImage *)screenshot;
- (struct NSImage *)defaultSiteIcon;
@end

