//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NotificationCenter/NSObject-Protocol.h>

@class NCListItemViewController, NSEvent;

@protocol NCWidgetListItemDelegate <NSObject>
- (void)widgetListItem:(NCListItemViewController *)arg1 mouseUp:(NSEvent *)arg2;
- (void)widgetListItem:(NCListItemViewController *)arg1 mouseDragged:(NSEvent *)arg2;
- (void)widgetListItem:(NCListItemViewController *)arg1 mouseDown:(NSEvent *)arg2;

@optional
- (void)didDeleteWidgetListItem:(NCListItemViewController *)arg1;
- (void)willDeleteWidgetListItem:(NCListItemViewController *)arg1;
- (struct NSEdgeInsets)innerInsetsForWidgetListItem:(NCListItemViewController *)arg1;
@end

