//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <PhotosUICore/PXPeopleHomeCollectionViewCell.h>

@class CAShapeLayer;

@interface PXPeopleHomeCollectionViewPlusCell : PXPeopleHomeCollectionViewCell
{
    CAShapeLayer *_plusShapeLayer;
}

@property(retain, nonatomic) CAShapeLayer *plusShapeLayer; // @synthesize plusShapeLayer=_plusShapeLayer;
- (void).cxx_destruct;
- (struct CGPath *)_createShapePathForBoundsRect:(struct CGRect)arg1;
- (void)_updatePlusShapeLayer;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

