//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray;

@interface SGMicrodataItemScope : NSObject
{
    NSMutableArray *_itemProps;
}

@property(readonly, nonatomic) NSArray *itemProps; // @synthesize itemProps=_itemProps;
- (void).cxx_destruct;
- (BOOL)isReferencedBy:(id)arg1;
- (void)addItemProp:(id)arg1;
- (id)init;

@end

