//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QTKit/QTGraphicsDevice.h>

__attribute__((visibility("hidden")))
@interface QTConcreteGraphicsDevice : QTGraphicsDevice
{
}

- (unsigned long long)retainCount;
- (id)autorelease;
- (void)release;
- (id)retain;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned int)IOServicePort;
- (unsigned int)displayMask;

@end

