//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <QTKit/QTMovieModernizerTrack.h>

__attribute__((visibility("hidden")))
@interface QTMovieModernizerLegacyQTTrackPassthrough : QTMovieModernizerTrack
{
}

- (BOOL)cleanup;
- (BOOL)startup;
- (id)initWithSourceAsset:(id)arg1 track:(id)arg2 forModernizer:(id)arg3;

@end

