//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DataDetectorsUI/DDAddressAction.h>

@class DDRemoteActionViewController;

@interface DDAddToAddressBookAction : DDAddressAction
{
}

- (void)adaptForPresentationInPopover:(_Bool)arg1;
- (void)prepareViewControllerForActionController:(id)arg1;
- (int)interactionType;
- (id)localizedName;
- (void)invalidate;

// Remaining properties
@property(retain, nonatomic) DDRemoteActionViewController *viewController; // @dynamic viewController;

@end

