//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDimension.h>

#import <Foundation/NSSecureCoding-Protocol.h>

@interface NSUnitFrequency : NSDimension <NSSecureCoding>
{
}

+ (id)_measurementWithNaturalScale:(id)arg1 system:(unsigned long long)arg2;
+ (id)nanohertz;
+ (id)microhertz;
+ (id)millihertz;
+ (id)hertz;
+ (id)kilohertz;
+ (id)megahertz;
+ (id)gigahertz;
+ (id)terahertz;
+ (id)baseUnit;

@end

