//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Automator/AMApplicationWorkflowPersonality.h>

@interface AMDictationCommandWorkflowPersonality : AMApplicationWorkflowPersonality
{
}

- (void)updateWorkflowMetaDataWithCommandProperties:(id)arg1 forDocument:(id)arg2;
- (id)syncCommandProperties:(id)arg1 atURL:(id)arg2;
- (id)commandPropertiesFromDocument:(id)arg1;
- (id)pluginHeaderViewController;
- (BOOL)finishSavingDocument:(id)arg1 forOperation:(unsigned long long)arg2 atURL:(id)arg3 error:(id *)arg4;
- (BOOL)canSaveDocument:(id)arg1 error:(id *)arg2;
- (id)infoStringForCompleteInstallationWithMetaData:(id)arg1;
- (id)imageRepresentation;
- (id)personalitySettingsDictionary;

@end

