//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface CNCustomActionSheetPresentation : NSObject
{
}

+ (id)prepareViewControllerForPresentation:(id)arg1 sourceView:(id)arg2 sourceRect:(struct CGRect)arg3 permittedArrowDirection:(unsigned long long)arg4 dismissHandler:(CDUnknownBlockType)arg5;

@end

