//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <PhotosPlayer/CAAnimationDelegate-Protocol.h>

@class NSString;

@interface ISTransitionApplier : NSObject <CAAnimationDelegate>
{
}

+ (id)defaultApplier;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)_setValue:(id)arg1 forKeyPath:(id)arg2 ofLayer:(id)arg3 withTransitionOptions:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)_applyAlpha:(double)arg1 scale:(double)arg2 blurRadius:(double)arg3 toLayer:(id)arg4 withTransitionOptions:(id)arg5 completion:(CDUnknownBlockType)arg6;
- (void)applyOutputInfo:(id)arg1 withTransitionOptions:(id)arg2 toPhotoLayer:(id)arg3 videoLayer:(id)arg4 crossfadeLayer:(id)arg5 containerLayer:(id)arg6 completion:(CDUnknownBlockType)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

