//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MNRoutePlanningDetails;
@protocol MNNavigationServiceReconnectorDelegate;

__attribute__((visibility("hidden")))
@interface MNNavigationServiceReconnector : NSObject
{
    id <MNNavigationServiceReconnectorDelegate> _delegate;
    MNRoutePlanningDetails *_routePlanningDetails;
}

@property(nonatomic) __weak id <MNNavigationServiceReconnectorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)_isValidRoutePlanningDetails:(id)arg1;
- (BOOL)reconnect;
- (void)finishReconnecting;
- (BOOL)isReconnecting;
- (id)initWithRoutePlanningDetails:(id)arg1;

@end

