//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <RemoteUI/RemoteUITableViewCell.h>

@class UILabel;

@interface RemoteUITableViewSubtitleAndValueCell : RemoteUITableViewCell
{
    UILabel *_valueLabel;
}

- (void).cxx_destruct;
- (void)setBackgroundColor:(id)arg1;
@property(readonly, nonatomic) UILabel *valueLabel;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

