//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (ABLEFunctional)
- (id)dictionaryByAddingEntriesFromDictionary:(id)arg1;
- (id)reduce:(CDUnknownBlockType)arg1 withInitialValue:(id)arg2;
- (id)keyMap:(CDUnknownBlockType)arg1;
- (id)map:(CDUnknownBlockType)arg1;
@end

