//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GEOPlatform : NSObject
{
}

+ (id)sharedPlatform;
+ (void)setIsRunningInGeod:(BOOL)arg1;
- (double)deviceScreenScale;
- (long long)deviceScreenHeightInPixels;
- (long long)deviceScreenWidthInPixels;
- (id)clientCapabilities;
- (BOOL)supportsNavigation;
- (BOOL)supportsRealisticTiles;
- (BOOL)mapsFeatureFreedomEnabled;
- (BOOL)_deviceSupportsNavigation;
- (id)hardwareIdentifier;
- (id)buildVersion;
- (id)osVersion;
- (id)productName;
- (id)_systemInfoDictionary;
- (BOOL)isInternalInstall;

@end

