//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface GEOPlaceDailyHours : NSObject
{
    struct _NSRange _dayOfWeekRange;
    NSArray *_openIntervals;
}

+ (id)dailyHours:(id)arg1 forDays:(struct _NSRange)arg2;
@property(readonly) NSArray *openIntervals; // @synthesize openIntervals=_openIntervals;
@property(readonly) struct _NSRange dayOfWeekRange; // @synthesize dayOfWeekRange=_dayOfWeekRange;
- (id)description;
- (void)dealloc;

@end

