//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CLLocation, CalGeocoder, EKTravelEngineHypothesis, EKTravelEngineOriginalEvent, EKTravelEngineThrottle, GEORouteHypothesizer, NSData;
@protocol OS_dispatch_queue;

@interface EKTravelEngineAgendaEntry : NSObject
{
    BOOL _dismissed;
    BOOL _geocodedEventEncountered;
    EKTravelEngineHypothesis *_latestHypothesis;
    CDUnknownBlockType _updateBlock;
    CDUnknownBlockType _entrySignificantlyChangedBlock;
    NSObject<OS_dispatch_queue> *_workQueue;
    NSObject<OS_dispatch_queue> *_callbackQueue;
    EKTravelEngineOriginalEvent *_originalEventInternal;
    EKTravelEngineThrottle *_throttle;
    CalGeocoder *_geocoder;
    GEORouteHypothesizer *_hypothesizer;
    CLLocation *_geoLocation;
    NSData *_mapKitHandle;
}

+ (double)_maximumAllowableTravelTime;
+ (double)fuzzyMaximumInitialUpdateIntervalBeforeStartDate;
@property(nonatomic) BOOL geocodedEventEncountered; // @synthesize geocodedEventEncountered=_geocodedEventEncountered;
@property(retain, nonatomic) NSData *mapKitHandle; // @synthesize mapKitHandle=_mapKitHandle;
@property(retain, nonatomic) CLLocation *geoLocation; // @synthesize geoLocation=_geoLocation;
@property(retain, nonatomic) GEORouteHypothesizer *hypothesizer; // @synthesize hypothesizer=_hypothesizer;
@property(retain, nonatomic) CalGeocoder *geocoder; // @synthesize geocoder=_geocoder;
@property(retain, nonatomic) EKTravelEngineThrottle *throttle; // @synthesize throttle=_throttle;
@property(retain, nonatomic) EKTravelEngineOriginalEvent *originalEventInternal; // @synthesize originalEventInternal=_originalEventInternal;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *callbackQueue; // @synthesize callbackQueue=_callbackQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *workQueue; // @synthesize workQueue=_workQueue;
@property(nonatomic) BOOL dismissed; // @synthesize dismissed=_dismissed;
@property(copy, nonatomic) CDUnknownBlockType entrySignificantlyChangedBlock; // @synthesize entrySignificantlyChangedBlock=_entrySignificantlyChangedBlock;
@property(copy, nonatomic) CDUnknownBlockType updateBlock; // @synthesize updateBlock=_updateBlock;
@property(retain, nonatomic) EKTravelEngineHypothesis *latestHypothesis; // @synthesize latestHypothesis=_latestHypothesis;
- (void).cxx_destruct;
- (void)_accountForGeocodedEventEncounter;
- (void)_updateWithHypothesis:(id)arg1;
- (void)_createHypothesizerForDestination:(id)arg1;
- (void)_createSyntheticHypothesis;
- (id)_generateDestination;
- (void)_setUpRouteMonitoring;
- (void)_enhanceLocation;
- (void)_clearEverything;
- (void)_sendFeedbackToHypothesizerForPostingNotification:(unsigned long long)arg1;
- (void)sendFeedbackForPostingLeaveNowNotification;
- (void)sendFeedbackForPostingLeaveByNotification;
@property(readonly, nonatomic) EKTravelEngineOriginalEvent *originalEvent;
- (void)reset;
- (void)updateWithOriginalEvent:(id)arg1;
- (id)init;

@end

