//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSApplication.h>

@interface NSApplication (ASKObjectScriptingSupport)
- (void)removeFromObjectsAtIndex:(unsigned long long)arg1;
- (void)removeObject:(id)arg1;
- (void)insertInObjects:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)addInObjects:(id)arg1;
- (id)objectAtIndex:(unsigned long long)arg1;
- (id)valueInObjectsWithUniqueID:(long long)arg1;
- (id)objects;
@end

