//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface _TVMusicPlaylistDecorator : NSObject
{
}

+ (id)playlistFolderWithImages:(id)arg1 size:(struct CGSize)arg2 upscaleAdjustment:(double)arg3 cornerRadius:(double)arg4;
+ (id)curatedPlaylistImageWithImages:(id)arg1 size:(struct CGSize)arg2 upscaleAdjustment:(double)arg3 cornerRadius:(double)arg4;
+ (id)playlistImageWithImages:(id)arg1 size:(struct CGSize)arg2 upscaleAdjustment:(double)arg3 cornerRadius:(double)arg4;

@end

