//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class TVSPlaybackState, TVSPlayer;

@interface TVBackgroundAudioController : NSObject
{
    TVSPlayer *_audioPlayer;
    unsigned long long _deactivationReasons;
    _Bool _deactivated;
    _Bool _stoppedOnDeactivation;
    double _delayedPlaybackInterval;
}

+ (id)sharedBackgroundAudioController;
- (void).cxx_destruct;
- (void)_cancelDelayedPlay;
- (void)_applicationDidRemoveDeactivationReason:(id)arg1;
- (void)_applicationWillAddDeactivationReason:(id)arg1;
- (void)_stop;
- (void)stop;
@property(readonly, nonatomic) TVSPlaybackState *state;
- (void)setCurrentMediaItemFromAudioElement:(id)arg1;
- (_Bool)playWithDelay:(double)arg1;
- (_Bool)play;
- (void)dealloc;
- (id)init;

@end

