//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionReusableView.h>

@interface UICollectionReusableView (TVMLKitAdditions)
@property(nonatomic, getter=tv_isFocused, setter=tv_setFocused:) _Bool tv_focused;
@property(nonatomic, getter=tv_isDisplayed, setter=tv_setDisplayed:) _Bool tv_displayed;
@end

