//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <HMFoundation/HMFMessage.h>

@interface HMFMessage (IDSAdditions)
- (_Bool)_supportsFeature:(unsigned long long)arg1 forCapabilitiesKey:(id)arg2;
- (_Bool)supportsRequestedFeature:(unsigned long long)arg1;
- (_Bool)supportsRequiredFeature:(unsigned long long)arg1;
@end

