//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface CPCompositorWatcher : NSObject
{
    NSString *mProfileUUID;
    NSArray *mUIDs;
    NSMutableArray *mRemainingUIDs;
    BOOL mDone;
}

- (_Bool)isDone;
- (id)getProfileUUID;
- (void)notificationReceived:(id)arg1;
- (id)gatherLoggedInUserUIDs;
- (void)setUIDs:(id)arg1;
- (id)getUIDs;
- (void)dealloc;
- (id)initForProfile:(id)arg1;

@end

