//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface WKMenuTarget : NSObject
{
    struct WebContextMenuProxyMac *_menuProxy;
}

+ (id)sharedMenuTarget;
- (void)forwardContextMenuAction:(id)arg1;
- (void)setMenuProxy:(struct WebContextMenuProxyMac *)arg1;
- (struct WebContextMenuProxyMac *)menuProxy;

@end

