//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WebKit/WKViewLayoutStrategy.h>

__attribute__((visibility("hidden")))
@interface WKViewDynamicSizeWithMinimumViewSizeLayoutStrategy : WKViewLayoutStrategy
{
    BOOL _isWaitingForCommit;
    BOOL _hasPendingLayout;
    double _lastCommittedViewScale;
}

- (void)willChangeLayoutStrategy;
- (void)didChangeFrameSize;
- (void)didEndLiveResize;
- (void)willStartLiveResize;
- (void)didChangeMinimumViewSize;
- (void)updateLayout;
- (void)_updateTransientScale:(double)arg1;
- (id)initWithPage:(struct WebPageProxy *)arg1 view:(id)arg2 mode:(unsigned int)arg3;

@end

