//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FinderKit/FINodeUIElement.h>

@class IKImageFlowView;

__attribute__((visibility("hidden")))
@interface FINodeFlowUIElement : FINodeUIElement
{
}

- (void)accessibilityPerformAction:(id)arg1;
- (id)accessibilityActionNames;
- (struct CGRect)frame;
- (void)setSelection:(_Bool)arg1;
- (_Bool)isSelected;
@property(readonly, retain, nonatomic) IKImageFlowView *containerView; // @dynamic containerView;

@end

