//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, NSURLRequest, NSURLResponse, QLPreviewParts;

@interface QLPreviewConverter : NSObject
{
    QLPreviewParts *_previewParts;
    NSDictionary *_options;
    NSString *_previewFileName;
    NSString *_previewUTI;
    NSURLRequest *_previewRequest;
    NSURLResponse *_previewResponse;
}

@property(readonly, nonatomic) QLPreviewParts *previewParts; // @synthesize previewParts=_previewParts;
@property(readonly, nonatomic) NSURLResponse *previewResponse; // @synthesize previewResponse=_previewResponse;
@property(readonly, nonatomic) NSURLRequest *previewRequest; // @synthesize previewRequest=_previewRequest;
@property(readonly, nonatomic) NSString *previewUTI; // @synthesize previewUTI=_previewUTI;
@property(readonly, nonatomic) NSString *previewFileName; // @synthesize previewFileName=_previewFileName;
- (void).cxx_destruct;

@end

