//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class BKItemUniqueIdentifier, NSArray, NSString;
@protocol BKItem, BKItem><BKItemProvider;

@protocol BKItem
- (NSArray *)itemPasteboardDataTypes;
- (id)itemPasteboardObjectForType:(NSString *)arg1;
- (BKItemUniqueIdentifier *)itemUniqueIdentifier;
- (BOOL)itemIsLeaf;
- (NSArray *)itemKeys;

@optional
- (id <BKItem><BKItemProvider>)itemParent;
- (id <BKItem>)parentItem;
@end

