//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NSObject (BrowserKitItemMagicAccessors)
- (id)browserKitConfigurationClassString;
- (Class)browserKitUnderlyingClass;
- (id)browserKitItemThumbnail;
- (id)browserKitItemIcon;
- (void)setBrowserKitSidebarValue:(id)arg1;
- (id)browserKitSidebarValue;
- (void)setBrowserKitItemIconAndDisplayName:(id)arg1;
- (id)browserKitItemIconAndDisplayName;
- (void)_browserKitFillInItemIconAndDisplayName:(id)arg1 withItemKeys:(id)arg2;
- (id)browserKitItemLabelColorAndDisplayName;
- (id)browserKitItemAcquisitionMakeAndModel;
- (id)browserKitItemPath;
- (id)browserKitItemURL;
- (id)browserKitItemKind;
- (id)browserKitItemContentModificationDate;
- (id)browserKitItemContentCreationDate;
- (id)browserKitItemPixelSize;
@end

