//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AccountsUI/NSObject-Protocol.h>

@class ACAccount, ACAccountType, ACUIAccountInfoViewController, ACUIAccountSetupViewController, NSArray, NSImage, NSSet, NSString, NSWindow;

@protocol ACUIPlugin <NSObject>
- (NSSet *)supportedAccountTypes;

@optional
- (NSImage *)logoForAccountType:(NSString *)arg1;
- (void)deleteAccount:(ACAccount *)arg1 inWindow:(NSWindow *)arg2;
- (NSArray *)dataclassesOrder;
- (NSSet *)uiDataclasses;
- (ACUIAccountSetupViewController *)setupViewControllerForAccountType:(ACAccountType *)arg1;
- (ACUIAccountInfoViewController *)infoViewControllerForAccount:(ACAccount *)arg1;
- (NSImage *)iconForAccountType:(NSString *)arg1;
@end

