//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <ISSupport/ISS_DAVRequest.h>

@interface ISS_DAVMakeCollection : ISS_DAVRequest
{
}

+ (id)makeCollectionRequestWithSession:(id)arg1 path:(id)arg2;
+ (id)makeCollectionRequestWithURL:(id)arg1;
- (void)finalizeOperation;
- (id)initMakeCollectionWithSession:(id)arg1 path:(id)arg2;
- (id)initMakeCollectionWithURL:(id)arg1;

@end

