//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class _NSAcceleratorButtonHelper, _NSButtonAnimationView;

__attribute__((visibility("hidden")))
@interface _NSButtonCellAux : NSObject
{
    _NSButtonAnimationView *_animator;
    _NSAcceleratorButtonHelper *acceleratorHelper;
    double _doubleValue;
    long long _maxAcceleratorLevel;
    double _acceleratorClickTimestamp;
    unsigned char _buttonType;
    BOOL _exceededInitialValue;
    BOOL _springLoaded;
    BOOL _springLoadingEmphasized;
    BOOL _animationsAllowed;
}

- (id)copyWithZone:(struct _NSZone *)arg1;

@end

