//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/_NSPboardTypeConverter.h>

@interface _NSFilenamesPboardTypeConverter : _NSPboardTypeConverter
{
}

+ (id)_getConvertedDataFromPasteboard:(id)arg1 securityScoped:(BOOL)arg2;
+ (void)_setConvertedData:(id)arg1 pboard:(struct __CFPasteboard *)arg2 generation:(long long)arg3 inItem:(void *)arg4;

@end

