//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/_NSEventObserver.h>

@interface _NSLocalEventObserver : _NSEventObserver
{
    BOOL _isAdditive;
}

+ (void)initialize;
- (void)recomputeObserverMask;
- (void)invalidate;
- (id)initMatchingEvents:(unsigned long long)arg1 handler:(CDUnknownBlockType)arg2;

@end

