//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSObject-Protocol.h>

@class NSColor, NSColorPickerMatrixView;

@protocol NSColorPickerMatrixViewDelegate <NSObject>

@optional
- (NSColor *)matrixColorPicker:(NSColorPickerMatrixView *)arg1 highlightColorForColor:(NSColor *)arg2;
- (void)matrixColorPicker:(NSColorPickerMatrixView *)arg1 selectedColor:(NSColor *)arg2;
@end

