//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSVisualEffectView.h>

@class NSThemeFrame, NSTrackingArea;

__attribute__((visibility("hidden")))
@interface NSTitlebarView : NSVisualEffectView
{
    BOOL _transparent;
    NSTrackingArea *_buttonGroupTrackingArea;
    NSThemeFrame *_associatedThemeFrame;
}

@property BOOL transparent; // @synthesize transparent=_transparent;
@property NSThemeFrame *associatedThemeFrame; // @synthesize associatedThemeFrame=_associatedThemeFrame;
- (id)_titleTextFieldView;
- (id)titleFont;
- (id)menuForEvent:(id)arg1;
- (void)rightMouseDown:(id)arg1;
- (void)mouseDown:(id)arg1;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)updateTrackingAreas;
- (void)_removeTrackingAreaIfNeeded;
- (BOOL)shouldSetFontSmoothingBackgroundColor;
- (void)dealloc;
- (void)resizeWithOldSuperviewSize:(struct CGSize)arg1;
- (BOOL)_shouldAddBorderLayer;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)accessibilityChildrenAttribute;
- (BOOL)accessibilityIsIgnored;

@end

