//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface NEHelperSystemProviderManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_queue> *_messageQueue;
    NSMutableDictionary *_IPCChannels;
}

+ (id)sharedManager;
@property(retain) NSMutableDictionary *IPCChannels; // @synthesize IPCChannels=_IPCChannels;
@property(readonly) NSObject<OS_dispatch_queue> *messageQueue; // @synthesize messageQueue=_messageQueue;
@property(readonly) NSObject<OS_dispatch_queue> *queue; // @synthesize queue=_queue;
- (void).cxx_destruct;
- (id)createResponseForMessageID:(long long)arg1 responseData:(id)arg2 enabled:(BOOL)arg3;
- (void)handleProviderEvent:(id)arg1 data:(id)arg2 responseHandler:(CDUnknownBlockType)arg3;
- (void)handleProviderEvent:(id)arg1 data:(id)arg2 configurationIdentifier:(id)arg3 responseHandler:(CDUnknownBlockType)arg4;
- (void)sendMessage:(id)arg1 overIPC:(id)arg2 identifier:(long long)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)getIdentifierOfConfigurationForPluginType:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (id)init;

@end

