//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CacheDelete/CDXPCService.h>

@class NSString;

@interface CDNamedXPCService : CDXPCService
{
    NSString *_xpcServiceName;
    unsigned long long _options;
}

@property(nonatomic) unsigned long long options; // @synthesize options=_options;
@property(retain, nonatomic) NSString *xpcServiceName; // @synthesize xpcServiceName=_xpcServiceName;
- (void).cxx_destruct;
- (void)obtainXPCConnection:(CDUnknownBlockType)arg1;
- (id)initWithInfo:(id)arg1;

@end

