//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TextureIO/TXRXCFileAttributes.h>

@interface TXRXCMipFileAttributes : TXRXCFileAttributes
{
    unsigned long long _level;
    unsigned long long _face;
}

@property(nonatomic) unsigned long long level; // @synthesize level=_level;
- (_Bool)doesSpecifyAllFaces;
- (void)specifyAllFaces;
@property(nonatomic) unsigned long long face;
- (id)init;

@end

