//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (Utilities)
+ (struct UIImage *)ic_imageWithColor:(struct UIColor *)arg1 size:(struct CGSize)arg2;
+ (struct UIImage *)fileIconForURL:(id)arg1 withPreferredSize:(struct CGSize)arg2;
+ (id)UIImageFromCIImage:(id)arg1;
+ (struct UIImage *)imageNamed:(id)arg1 withTint:(struct UIColor *)arg2;
+ (struct UIImage *)ic_imageWithContentsOfURL:(id)arg1;
- (struct UIImage *)decodeInBackground;
- (void)decodeWithCompletion:(CDUnknownBlockType)arg1;
- (id)ic_imageDataWithUTType:(id)arg1;
- (id)ic_PNGData;
- (id)ic_JPEGData;
- (struct UIImage *)imageFromRect:(struct CGRect)arg1;
- (struct UIImage *)scaledImageWithSize:(struct CGSize)arg1 scale:(double)arg2;
- (struct UIImage *)scaledImageMaxDimension:(double)arg1 scale:(double)arg2;
- (struct UIImage *)scaledImageMinDimension:(double)arg1 scale:(double)arg2;
@end

