//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSValueTransformer.h>

@class NSArray;

@interface NSValueTransformer (SPCValueTransformerAdditions)
+ (BOOL)_addMethodWithSelector:(SEL)arg1 isClassMethod:(BOOL)arg2 forClass:(Class)arg3 withImplementation:(CDUnknownFunctionPointerType)arg4;
+ (void)enumerateValueTransformersUsingBlock:(CDUnknownBlockType)arg1;
+ (id)inputClasses;
+ (id)valueTransformerForTransformedClass:(Class)arg1 withInputClasses:(id)arg2 transformation:(CDUnknownBlockType)arg3 reverseTransformation:(CDUnknownBlockType)arg4;
+ (id)valueTransformerForTransformedClass:(Class)arg1 withInputClasses:(id)arg2 transformation:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) BOOL allowsReverseTransformation;
@property(readonly, nonatomic) Class transformedValueClass;
@property(readonly, copy, nonatomic) NSArray *inputClasses;
@end

