//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSURL;

@interface SPCAssetManagerSessionItem : NSObject
{
    NSURL *_fileURL;
}

+ (id)importSessionItemWithFileURL:(id)arg1;
@property(copy) NSURL *fileURL; // @synthesize fileURL=_fileURL;
- (void)dealloc;
- (id)initWithSessionType:(long long)arg1 andFileURL:(id)arg2;

@end

