//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class SPCExpressionTokenizer;

@interface SPCExpressionParser : NSObject
{
    SPCExpressionTokenizer *_tokenizer;
}

+ (id)parserWithTokenizer:(id)arg1 error:(id *)arg2;
+ (id)parserWithString:(id)arg1 error:(id *)arg2;
@property(readonly, retain, nonatomic) SPCExpressionTokenizer *tokenizer; // @synthesize tokenizer=_tokenizer;
- (id)parsedExpressionWithError:(id *)arg1;
- (void)dealloc;
- (id)initWithTokenizer:(id)arg1 error:(id *)arg2;
- (id)initWithString:(id)arg1 error:(id *)arg2;

@end

