//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol SPCRenderDelegate;

@interface SPCRenderer : NSObject
{
    id <SPCRenderDelegate> _renderDelegate;
}

+ (id)sharedRenderer;
@property(retain, nonatomic) id <SPCRenderDelegate> renderDelegate; // @synthesize renderDelegate=_renderDelegate;
- (id)imageForLayer:(id)arg1 state:(id)arg2 scaleFactor:(double)arg3;
- (id)imageForElementPart:(id)arg1 state:(id)arg2 scaleFactor:(double)arg3;
- (void)dealloc;

@end

