//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <CoreSpectrum/NSCoding-Protocol.h>
#import <CoreSpectrum/NSCopying-Protocol.h>

@class SPCPosition, SPCSize;

@interface SPCRect : NSObject <NSCopying, NSCoding>
{
    SPCPosition *_origin;
    SPCSize *_size;
}

+ (id)rectWithOrigin:(id)arg1 size:(id)arg2;
+ (id)zeroRect;
@property(copy, nonatomic) SPCSize *size; // @synthesize size=_size;
@property(copy, nonatomic) SPCPosition *origin; // @synthesize origin=_origin;
- (struct CGRect)absoluteRectForEnclosingRect:(struct CGRect)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)initWithOrigin:(id)arg1 size:(id)arg2;

@end

