//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MediaPlayer/MPModelRequest.h>

@interface MPStoreFollowRecommendationsRequest : MPModelRequest
{
}

- (id)newOperationWithResponseHandler:(CDUnknownBlockType)arg1;
- (void)setItemSortDescriptors:(id)arg1;
- (void)setSectionSortDescriptors:(id)arg1;
- (void)setAllowsDeferringExpensiveProperties:(_Bool)arg1;
- (void)setItemProperties:(id)arg1;
- (void)setSectionProperties:(id)arg1;
- (Class)sectionClass;
- (void)setSectionClass:(Class)arg1;
- (Class)itemClass;
- (void)setItemClass:(Class)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

