//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class AVURLAsset, AVWeakReference, NSError, NSNumber, NSURL;

@interface AVAssetDownloadSessionInternal : NSObject
{
    AVWeakReference *weakReference;
    struct OpaqueFigPlayer *player;
    struct OpaqueFigPlaybackItem *playbackItem;
    const struct OpaqueFigAsset *figAsset;
    struct dispatch_queue_s *readWriteQueue;
    long long status;
    NSError *error;
    long long priority;
    NSURL *URL;
    NSURL *destinationURL;
    unsigned long long downloadToken;
    NSNumber *cachePrimingDownloadTokenNum;
    AVURLAsset *asset;
    struct CMBaseObject *assetDownloader;
}

@end

