//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <AVFoundation/AVVideoCompositing-Protocol.h>

@class CIContext, NSDictionary, NSString;

@interface AVCoreImageFilterCustomVideoCompositor : NSObject <AVVideoCompositing>
{
    struct dispatch_group_s *_filteringRequestsInFlight;
    BOOL _shouldCancelAllRequests;
    struct CGColorSpace *_dstColorSpace;
    struct dispatch_queue_s *_defaultCIContextThreadSafety;
    CIContext *_defaultCIContext;
}

+ (void)initialize;
@property(retain, nonatomic) struct CGColorSpace *dstColorSpace; // @synthesize dstColorSpace=_dstColorSpace;
@property BOOL shouldCancelAllRequests; // @synthesize shouldCancelAllRequests=_shouldCancelAllRequests;
- (void)cancelAllPendingVideoCompositionRequests;
- (void)startVideoCompositionRequest:(id)arg1;
- (id)defaultCIContext;
@property(readonly) struct dispatch_group_s *filteringRequestsInFlight; // @synthesize filteringRequestsInFlight=_filteringRequestsInFlight;
- (void)renderContextChanged:(id)arg1;
@property(readonly, nonatomic) NSDictionary *requiredPixelBufferAttributesForRenderContext;
@property(readonly, nonatomic) NSDictionary *sourcePixelBufferAttributes;
- (void)finalize;
- (void)dealloc;
- (void)_willDeallocOrFinalize;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

