//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface VCPVideoMetaAnalyzer : NSObject
{
}

+ (id)analyzerForTrackType:(id)arg1 withTransform:(struct CGAffineTransform)arg2;
- (id)results;
- (int)processMetadataGroup:(id)arg1 flags:(unsigned long long *)arg2;

@end

