//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSError, _PFUbiquityRecordImportOperation;

@protocol _PFUbiquityRecordImportOperationDelegate
- (void)operationWasInterruptedDuringImport:(_PFUbiquityRecordImportOperation *)arg1;
- (void)operation:(_PFUbiquityRecordImportOperation *)arg1 failedWithError:(NSError *)arg2;
- (void)operationDidFinish:(_PFUbiquityRecordImportOperation *)arg1;
@end

