//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FrontBoardServices/FBSSettingsDiffInspector.h>

@interface FBSSceneClientSettingsDiffInspector : FBSSettingsDiffInspector
{
}

- (void)observePreferredSceneHostIdentifierWithBlock:(CDUnknownBlockType)arg1;
- (void)observeOcclusionsWithBlock:(CDUnknownBlockType)arg1;
- (void)observePreferredInterfaceOrientationWithBlock:(CDUnknownBlockType)arg1;
- (void)observePreferredLevelWithBlock:(CDUnknownBlockType)arg1;
- (void)observeClassWithBlock:(CDUnknownBlockType)arg1;

@end

