//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSXPCConnection;

@interface WLKApplicationWorkspace : NSObject
{
    NSXPCConnection *_connection;
}

+ (id)defaultWorkspace;
- (void).cxx_destruct;
- (id)_proxy;
- (id)_connection;
- (void)fetchApplicationsOfType:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;

@end

