//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <WatchListKit/WLKServerConfigurationRequestOperationDelegate-Protocol.h>

@class NSArray, NSDate, NSDictionary, NSMutableDictionary, NSOperationQueue, NSString;
@protocol OS_dispatch_queue;

@interface WLKServerConfiguration : NSObject <WLKServerConfigurationRequestOperationDelegate>
{
    NSObject<OS_dispatch_queue> *_accessQueue;
    NSOperationQueue *_fetchQueue;
    NSDictionary *_channelsByID;
    NSDictionary *_dictionary;
    int _didChangeNotificationToken;
    NSDictionary *_endpointsDictionary;
    NSOperationQueue *_operationQueue;
    NSDictionary *_requiredRequestKeyValuePairsDictionary;
    NSMutableDictionary *_completions;
    unsigned long long _cachedEnvironmentHash;
    NSString *_nextEK;
    _Bool _loaded;
    NSArray *_orderedChannels;
    NSDictionary *_serverRoutesDictionary;
    NSDate *_expirationDate;
    CDUnknownBlockType _fetchCompletionHandler;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSDictionary *requiredRequestKeyValuePairsDictionary; // @synthesize requiredRequestKeyValuePairsDictionary=_requiredRequestKeyValuePairsDictionary;
@property(copy, nonatomic) CDUnknownBlockType fetchCompletionHandler; // @synthesize fetchCompletionHandler=_fetchCompletionHandler;
@property(copy, nonatomic) NSDate *expirationDate; // @synthesize expirationDate=_expirationDate;
@property(readonly, copy, nonatomic) NSDictionary *serverRoutesDictionary; // @synthesize serverRoutesDictionary=_serverRoutesDictionary;
@property(readonly, copy, nonatomic) NSArray *orderedChannels; // @synthesize orderedChannels=_orderedChannels;
@property(readonly, nonatomic, getter=isLoaded) _Bool loaded; // @synthesize loaded=_loaded;
- (void).cxx_destruct;
- (void)_clearCompletionsForEnvironment:(id)arg1;
- (id)_completionsForEnvironment:(id)arg1;
- (void)_addCompletion:(CDUnknownBlockType)arg1 forEnvironment:(id)arg2;
- (id)_prevCachePath;
- (id)_cachePath;
- (id)_cacheDir;
- (_Bool)_writeToDisk:(id)arg1;
- (id)_readFromDisk;
- (id)_readFromDiskPath:(id)arg1;
- (id)_diskCacheDebug;
- (void)_setNextEK:(id)arg1;
- (void)_invalidateCache;
- (void)_handleLibraryDidChangeNotification:(id)arg1;
- (_Bool)_needCacheRefresh;
- (void)_fetchConfigurationSynchronously;
- (void)_updateWithResponse:(id)arg1 expirationDate:(id)arg2 environmentHash:(unsigned long long)arg3;
- (void)_synchronizeWithCacheAndNotifySelf:(_Bool)arg1 others:(_Bool)arg2;
- (void)applicationConfigRequestOperationDidFail:(id)arg1;
- (void)applicationConfigRequestOperationDidFinish:(id)arg1;
- (id)serverRouteForKey:(id)arg1;
- (void)fetchConfiguration:(CDUnknownBlockType)arg1;
- (id)APIBaseURL;
@property(readonly, copy, nonatomic) NSDictionary *channels;
- (id)endpointForKey:(id)arg1;
@property(readonly, nonatomic) NSDictionary *dictionary;
- (id)_operationQueue;
- (void)dealloc;
- (id)init;
- (id)initOffline;
- (void)_commonInit;
- (id)_init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

