//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary;

@interface WLKServerConfigurationResponse : NSObject
{
    NSDictionary *_dictionary;
    NSDictionary *_endpointsDictionary;
    NSDictionary *_serverRoutesDictionary;
    NSDictionary *_requiredRequestKeyValuePairsDictionary;
    unsigned long long _expirationInSeconds;
    NSDictionary *_channelsByID;
    NSArray *_orderedChannels;
}

@property(readonly, copy, nonatomic) NSArray *orderedChannels; // @synthesize orderedChannels=_orderedChannels;
@property(readonly, copy, nonatomic) NSDictionary *channelsByID; // @synthesize channelsByID=_channelsByID;
@property(readonly, nonatomic) unsigned long long expirationInSeconds; // @synthesize expirationInSeconds=_expirationInSeconds;
@property(readonly, nonatomic) NSDictionary *requiredRequestKeyValuePairsDictionary; // @synthesize requiredRequestKeyValuePairsDictionary=_requiredRequestKeyValuePairsDictionary;
@property(readonly, nonatomic) NSDictionary *serverRoutesDictionary; // @synthesize serverRoutesDictionary=_serverRoutesDictionary;
@property(readonly, nonatomic) NSDictionary *endpointsDictionary; // @synthesize endpointsDictionary=_endpointsDictionary;
@property(readonly, nonatomic) NSDictionary *dictionary; // @synthesize dictionary=_dictionary;
- (void).cxx_destruct;
- (id)init;
- (id)initWithDictionary:(id)arg1;

@end

