//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

@interface WLKUserEnvironment : NSObject
{
    NSString *_DSID;
    NSString *_storeFrontIdentifier;
    NSString *_localeIdentifier;
    NSDictionary *_entitlements;
    NSString *_restrictions;
    NSArray *_consentedBrands;
}

+ (void)setCurrentEnvironmentForTesting:(id)arg1;
+ (id)currentEnvironment;
@property(retain, nonatomic) NSArray *consentedBrands; // @synthesize consentedBrands=_consentedBrands;
@property(retain, nonatomic) NSString *restrictions; // @synthesize restrictions=_restrictions;
@property(retain, nonatomic) NSDictionary *entitlements; // @synthesize entitlements=_entitlements;
@property(retain, nonatomic) NSString *localeIdentifier; // @synthesize localeIdentifier=_localeIdentifier;
@property(retain, nonatomic) NSString *storeFrontIdentifier; // @synthesize storeFrontIdentifier=_storeFrontIdentifier;
@property(retain, nonatomic) NSString *DSID; // @synthesize DSID=_DSID;
- (void).cxx_destruct;
- (unsigned long long)_hashForStoreStuff;
- (unsigned long long)hash;
- (_Bool)isEqualToEnvironment:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)init;

@end

