//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TVServices/NSObject-Protocol.h>

@class NSError, TVSExternalControlSystem;

@protocol TVSExternalControlSystemDelegate <NSObject>

@optional
- (void)externalControlSystemDidRequestAlternateRouteVolumeDown:(TVSExternalControlSystem *)arg1;
- (void)externalControlSystemDidRequestAlternateRouteVolumeUp:(TVSExternalControlSystem *)arg1;
- (void)externalControlSystem:(TVSExternalControlSystem *)arg1 didFinishLearningAction:(int)arg2;
- (void)externalControlSystem:(TVSExternalControlSystem *)arg1 didCompleteLearningAction:(int)arg2 withResult:(_Bool)arg3 error:(NSError *)arg4;
- (void)externalControlSystem:(TVSExternalControlSystem *)arg1 didLearnAction:(int)arg2 withProgress:(double)arg3;
- (void)externalControlSystem:(TVSExternalControlSystem *)arg1 willStartLearningAction:(int)arg2;
- (void)externalControlSystem:(TVSExternalControlSystem *)arg1 didReceiveRequest:(long long)arg2;
- (void)externalControlSystem:(TVSExternalControlSystem *)arg1 didReceiveDeviceEvent:(long long)arg2;
- (void)externalControlSystem:(TVSExternalControlSystem *)arg1 didCompleteAction:(int)arg2 withResult:(_Bool)arg3 error:(NSError *)arg4;
- (void)externalControlSystem:(TVSExternalControlSystem *)arg1 didChangeLinkStatus:(_Bool)arg2;
- (void)externalControlSystem:(TVSExternalControlSystem *)arg1 didChangeReadyStatus:(_Bool)arg2;
- (void)externalControlSystem:(TVSExternalControlSystem *)arg1 didHandleRemoteControlButtonReleased:(long long)arg2;
- (void)externalControlSystem:(TVSExternalControlSystem *)arg1 didHandleRemoteControlButtonPressed:(long long)arg2;
- (void)externalControlSystemDidResignActiveSource:(TVSExternalControlSystem *)arg1;
- (void)externalControlSystemDidBecomeActiveSource:(TVSExternalControlSystem *)arg1;
- (void)externalControlSystemDidUpdatePolicy:(TVSExternalControlSystem *)arg1;
- (void)externalControlSystemDidChangeTopology:(TVSExternalControlSystem *)arg1;
@end

