//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IOBluetooth/IOBluetoothDevice.h>

@interface IOBluetoothDevice (IOBluetoothDeviceImages)
+ (id)imageForSystemIconType:(unsigned int)arg1 ofSize:(struct CGSize)arg2;
- (id)image;
- (id)loadImageFromBundle:(id)arg1 withResourceNamed:(id)arg2;
- (id)loadImageFromBundleID:(id)arg1 withResourceNamed:(id)arg2;
@end

