//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Slideshows/MCAnimationKeyframe.h>

@interface MCAnimationKeyframe1D : MCAnimationKeyframe
{
    float mValue;
}

+ (id)keyframeWithScalar:(float)arg1 atTime:(double)arg2 offsetKind:(int)arg3;
+ (id)keyframeWithScalar:(float)arg1 atTime:(double)arg2;
@property(nonatomic) float value; // @synthesize value=mValue;
- (void)_copySelfToSnapshot:(id)arg1;
- (id)description;
- (id)xmlElement;
- (id)imprint;
- (id)initWithImprint:(id)arg1;

@end

