//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class CNContactStore;

@interface IMAssistantMessageHandler : NSObject
{
    CNContactStore *_contactStore;
}

- (void).cxx_destruct;
- (id)INPersonsToDictionary:(id)arg1;
- (id)INPersonToDictionary:(id)arg1;
- (id)INPersonsForCNContactsArray:(id)arg1;
- (id)INPersonsForCNContacts:(id)arg1;
- (id)INPersonForCNContact:(id)arg1 withDisplayName:(id)arg2;
- (id)INPersonForCNContact:(id)arg1;
- (id)IMPersonForCNContact:(id)arg1;
- (id)fetchContactMatchingIntentPerson:(id)arg1;
@property(readonly, nonatomic) CNContactStore *contactStore;

@end

