//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MapKit/MKUserLocationHeadingConeLayer.h>

__attribute__((visibility("hidden")))
@interface _MKGemUserLocationHeadingConeLayer : MKUserLocationHeadingConeLayer
{
}

- (id)_headingImage:(struct CGPoint *)arg1;
- (void)updateHeadingAccuracy:(double)arg1 previousAccuracy:(double)arg2;

@end

