//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <InputMethodKit/IMKTextInput-Protocol.h>
#import <InputMethodKit/IMKTextInput_FunctionRowUI-Protocol.h>
#import <InputMethodKit/IMKUnicodeTextInput-Protocol.h>
#import <InputMethodKit/IMKXPCSupport-Protocol.h>
#import <InputMethodKit/IMTSMSupport-Protocol.h>

@protocol IMKTextInput_Full <IMKTextInput, IMKUnicodeTextInput, IMTSMSupport, IMKXPCSupport, IMKTextInput_FunctionRowUI>
@end

