//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <DataDetectorsCore/DDErrorRegexp.h>

#import <DataDetectorsCore/NSCopying-Protocol.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface DDVariableNotFoundError : DDErrorRegexp <NSCopying>
{
    NSString *_name;
}

- (int)splitRegexpWithDelegate:(id)arg1 owner:(id)arg2;
- (void)dealloc;
- (id)initWithVariableName:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

