//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class AVPlayerViewController, NSObject, TVSVideoView, TVVideoBorderView, UIView, _UIFloatingContentView;
@protocol TVMainVideoViewControllerDelegate, TVSAVFPlayback;

@interface TVMainVideoViewController : UIViewController
{
    _Bool _acceptsFocus;
    _Bool _useAVKit;
    _Bool _videoViewHidden;
    id <TVMainVideoViewControllerDelegate> _delegate;
    NSObject<TVSAVFPlayback> *_player;
    AVPlayerViewController *_avPlayerViewController;
    double _videoViewAlpha;
    _UIFloatingContentView *_floatingContentView;
    TVSVideoView *_videoView;
    UIView *_playbackView;
    TVVideoBorderView *_borderView;
}

@property(retain, nonatomic) TVVideoBorderView *borderView; // @synthesize borderView=_borderView;
@property(retain, nonatomic) UIView *playbackView; // @synthesize playbackView=_playbackView;
@property(retain, nonatomic) TVSVideoView *videoView; // @synthesize videoView=_videoView;
@property(retain, nonatomic) _UIFloatingContentView *floatingContentView; // @synthesize floatingContentView=_floatingContentView;
@property(nonatomic) double videoViewAlpha; // @synthesize videoViewAlpha=_videoViewAlpha;
@property(nonatomic, getter=isVideoViewHidden) _Bool videoViewHidden; // @synthesize videoViewHidden=_videoViewHidden;
@property(retain, nonatomic) AVPlayerViewController *avPlayerViewController; // @synthesize avPlayerViewController=_avPlayerViewController;
@property(nonatomic) _Bool useAVKit; // @synthesize useAVKit=_useAVKit;
@property(retain, nonatomic) NSObject<TVSAVFPlayback> *player; // @synthesize player=_player;
@property(nonatomic) _Bool acceptsFocus; // @synthesize acceptsFocus=_acceptsFocus;
@property(nonatomic) __weak id <TVMainVideoViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (void)loadView;
- (void)didUpdateFocusInContext:(id)arg1 withAnimationCoordinator:(id)arg2;
- (void)_addPlaybackView:(id)arg1;
- (void)_handleSelectButton:(id)arg1;
- (void)_didSelect;
- (void)preserveVideoViewForReuse;
- (id)initWithPlayer:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

