//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TVKit/NSObject-Protocol.h>

@class TVTransportBarThumbnailView;

@protocol TVTransportBarThumbnailViewDelegate <NSObject>
- (void)didHideThumbnailView:(TVTransportBarThumbnailView *)arg1 fromTextMode:(_Bool)arg2;
- (void)willHideThumbnailView:(TVTransportBarThumbnailView *)arg1;
- (void)didShowThumbnailView:(TVTransportBarThumbnailView *)arg1;
- (void)willShowThumbnailView:(TVTransportBarThumbnailView *)arg1;
@end

