//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FrontBoardServices/FBSSceneParameters.h>

@class FBSDisplay, FBSSceneClientSettings, FBSSceneSettings;

@interface FBSMutableSceneParameters : FBSSceneParameters
{
}

- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)updateClientSettingsWithBlock:(CDUnknownBlockType)arg1;
- (void)updateSettingsWithBlock:(CDUnknownBlockType)arg1;

// Remaining properties
@property(copy, nonatomic) FBSSceneClientSettings *clientSettings; // @dynamic clientSettings;
@property(copy, nonatomic) FBSDisplay *display; // @dynamic display;
@property(copy, nonatomic) FBSSceneSettings *settings; // @dynamic settings;

@end

