//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <WatchListKitUI/NSObject-Protocol.h>

@class TVCarouselView;

@protocol TVCarouselViewDelegate <NSObject>

@optional
- (void)carouselViewDidScroll:(TVCarouselView *)arg1;
- (void)carouselView:(TVCarouselView *)arg1 didPlayItemAtIndex:(unsigned long long)arg2;
- (void)carouselView:(TVCarouselView *)arg1 didSelectItemAtIndex:(unsigned long long)arg2;
- (void)carouselView:(TVCarouselView *)arg1 didFocusItemAtIndex:(unsigned long long)arg2;
@end

