//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Install/IFInstallQueueElement.h>

@class IFInstallQueue;

@interface IFEndOfInstallElement : IFInstallQueueElement
{
    IFInstallQueue *_installQueue;
    int _installKey;
}

- (long long)run;
- (void)_addAppRegisterElementWithPaths:(id)arg1;
- (id)description;
- (id)logDescription;
- (void)dealloc;
- (id)initWithSessionState:(id)arg1 installQueue:(id)arg2;

@end

