//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSAnimation.h>

@class SGTAnimationWindowEffect;

__attribute__((visibility("hidden")))
@interface SGTWindowAnimation : NSAnimation
{
    SGTAnimationWindowEffect *_windowEffect;
}

- (float)currentValue;
- (void)setCurrentProgress:(float)arg1;
@property(readonly) SGTAnimationWindowEffect *windowEffect;
- (void)discardWindowEffect;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

