//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKBRenderFactory10Key.h>

__attribute__((visibility("hidden")))
@interface UIKBRenderFactory10Key_Portrait : UIKBRenderFactory10Key
{
}

- (void)_customizeTraits:(id)arg1 forPopupForKey:(id)arg2 withRenderingContext:(id)arg3 keycapsFontName:(id)arg4;
- (void)setupLayoutSegments;
- (double)controlColumnWidthFactor;
- (struct CGPoint)dictationKeyTextOffset;
- (struct CGPoint)globeKeyTextOffset;
- (id)muttitapReverseKeyImageName;
- (id)multitapCompleteKeyImageName;
- (struct UIEdgeInsets)wideShadowPaddleInsets;

@end

