//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <EventKit/EKProtocolCalendar-Protocol.h>
#import <EventKit/EKProtocolMutableObject-Protocol.h>

@class NSString, NSURL;
@protocol EKProtocolCalendarSource;

@protocol EKProtocolMutableCalendar <EKProtocolCalendar, EKProtocolMutableObject>
@property(copy, nonatomic) NSURL *publishURL;
@property(copy, nonatomic) NSString *title;
@property(copy, nonatomic) NSString *notes;
@property(nonatomic) BOOL ignoreAlarms;
@property(nonatomic) int displayOrder;
@property(copy, nonatomic) id <EKProtocolCalendarSource> containerSource;
@property(copy, nonatomic) NSString *symbolicColorName;
@property(copy, nonatomic) NSString *colorString;
- (void)setSuppressEventSchedulingNotifications:(BOOL)arg1;
@end

