//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSLock, NSXPCConnection;
@protocol ASDJobManagerClient;

@interface ASDJobManagerClientConnection : NSObject
{
    NSXPCConnection *_connection;
    id <ASDJobManagerClient> _delegate;
    _Bool _invalidated;
    NSLock *_lock;
}

- (void).cxx_destruct;
- (void)_call:(CDUnknownBlockType)arg1;
- (void)didUpdateStates:(id)arg1;
- (void)didUpdateProgress:(id)arg1;
- (void)didCompleteJobs:(id)arg1 finalPhases:(id)arg2;
- (void)didChangeJobs:(id)arg1;
- (void)invalidate;
- (void)dealloc;
- (id)initWithConnection:(id)arg1 delegate:(id)arg2;

@end

