//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <AppleScriptObjC/BADescriptorTranslation-Protocol.h>

@interface BAImmediateData : NSObject <BADescriptorTranslation>
{
    id _obj;
}

- (id)__shim;
- (id)__descriptor;
- (void)dealloc;
- (id)initWithObject:(id)arg1;

@end

