//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SearchUI/NSObject-Protocol.h>

@class NUIContainerStackView, UIView;

@protocol NUIContainerStackViewDelegate <NSObject>

@optional
- (void)containerStackViewDidLayoutArrangedSubviews:(NUIContainerStackView *)arg1;
- (struct CGRect)containerStackView:(NUIContainerStackView *)arg1 layoutFrameForArrangedSubview:(UIView *)arg2 withProposedFrame:(struct CGRect)arg3;
- (struct UIEdgeInsets)containerStackView:(NUIContainerStackView *)arg1 minimumSpacingAdjecentToArrangedSubview:(UIView *)arg2;
- (struct CGSize)containerStackView:(NUIContainerStackView *)arg1 systemLayoutSizeFittingSize:(struct CGSize)arg2 forArrangedSubview:(UIView *)arg3;
- (void)containerStackViewDidInvalidateIntrinsicContentSize:(NUIContainerStackView *)arg1;
@end

