//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <TelephonyUtilities/NSObject-Protocol.h>

@class NSDictionary;
@protocol TUCallProviderManagerDataSourceDelegate;

@protocol TUCallProviderManagerDataSource <NSObject>
@property(nonatomic) __weak id <TUCallProviderManagerDataSourceDelegate> delegate;
@property(readonly, copy, nonatomic) NSDictionary *providersByIdentifier;
- (void)invalidate;
- (void)blockUntilInitialStateReceived;
@end

