//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface IPMessageXMLParser : NSObject
{
}

+ (id)dateFormatter;
+ (id)xmlElementForEvent:(id)arg1;
+ (id)xmlDocumentForMessages:(id)arg1 outputOptions:(unsigned long long)arg2;
+ (id)messagesByParsingXMLURL:(id)arg1;

@end

