//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface CKOperationFlowControlManager : NSObject
{
    NSMutableDictionary *_flowControlledOperationClasses;
}

@property(readonly) NSMutableDictionary *flowControlledOperationClasses; // @synthesize flowControlledOperationClasses=_flowControlledOperationClasses;
- (void).cxx_destruct;
- (void)unlimitAllOperations;
- (void)limitOperation:(id)arg1 retryAfter:(id)arg2;
- (double)secondsUntilUnlimited:(id)arg1;
- (BOOL)isOperationLimited:(id)arg1;
- (id)statusReport;
- (id)init;

@end

