//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CalendarAgentLink/CalStoreRemoteManagedAccount.h>

@interface CalStoreRemoteManagedCalDAVAccount : CalStoreRemoteManagedAccount
{
    BOOL _useKerberos;
}

+ (BOOL)supportsSecureCoding;
@property(nonatomic) BOOL useKerberos; // @synthesize useKerberos=_useKerberos;
- (void)encodeWithCoder:(id)arg1;
- (void)setPassword:(id)arg1;
- (id)password;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;

@end

