//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIActivityIndicatorView, UILabel;

@interface VideosExtrasActivityIndicator : UIView
{
    UILabel *_titleLabel;
    UIActivityIndicatorView *_spinner;
}

- (void).cxx_destruct;
- (void)setAlpha:(double)arg1;
- (struct CGSize)intrinsicContentSize;
- (id)initWithElement:(id)arg1;

@end

