//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface QLThumbnailDescriptor : NSObject
{
    double _scaleFactor;
    struct CGSize _size;
}

+ (id)descriptorWithSize:(struct CGSize)arg1 scaleFactor:(double)arg2;
@property double scaleFactor; // @synthesize scaleFactor=_scaleFactor;
@property struct CGSize size; // @synthesize size=_size;

@end

