//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol QLPreviewControllerStateProtocolHostOnly;

__attribute__((visibility("hidden")))
@interface QLStateManagerProxy : NSObject
{
    id <QLPreviewControllerStateProtocolHostOnly> _stateManager;
}

@property __weak id <QLPreviewControllerStateProtocolHostOnly> stateManager; // @synthesize stateManager=_stateManager;
- (void).cxx_destruct;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)dropMethod;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (_Bool)respondsToSelector:(SEL)arg1;

@end

