//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SAObjects/SADomainCommand.h>

@interface SAMPEnableShuffle : SADomainCommand
{
}

+ (id)enableShuffleWithDictionary:(id)arg1 context:(id)arg2;
+ (id)enableShuffle;
- (BOOL)requiresResponse;
@property(nonatomic) BOOL enable;
- (id)encodedClassName;
- (id)groupIdentifier;

@end

