//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface _Geometry : NSObject
{
    unsigned int _vao;
    unsigned int _vbo;
}

@property(nonatomic) unsigned int vbo; // @synthesize vbo=_vbo;
@property(nonatomic) unsigned int vao; // @synthesize vao=_vao;
- (void)createGeometry:(const float *)arg1 count:(unsigned long long)arg2 useWeights:(_Bool)arg3;
- (void)createGeometry:(const float *)arg1 count:(unsigned long long)arg2;

@end

