//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface NTKAstronomyDummy_ClientSideAnimation : NSObject
{
}

- (void)stop;
- (void)start;
- (void)setCompletion:(CDUnknownBlockType)arg1;
- (void)setApplier:(CDUnknownBlockType)arg1;
- (void)setTimingFunction:(id)arg1;
- (void)setDuration:(double)arg1;

@end

