//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <NanoTimeKitCompanion/NSObject-Protocol.h>

@class NTKComplication, NTKComplicationDisplayWrapperView, NTKComplicationLayoutRule, NTKComplicationPickerView;

@protocol NTKComplicationPickerViewDataSource <NSObject>
- (NTKComplicationLayoutRule *)complicationPickerView:(NTKComplicationPickerView *)arg1 layoutRuleForComplicationDisplay:(NTKComplicationDisplayWrapperView *)arg2;
- (void)complicationPickerView:(NTKComplicationPickerView *)arg1 getDisplay:(id *)arg2 controller:(id *)arg3 forComplication:(NTKComplication *)arg4;
@end

