//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSMutableData.h>

@interface NSMutableData (NSMutableDataObjcTypeSerialization)
- (void)serializeDataAt:(const void *)arg1 ofObjCType:(const char *)arg2 context:(id)arg3;
@end

