//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

__attribute__((visibility("hidden")))
@interface __NSCFTCPIO_BlockCallbacks_Referent : NSObject
{
    struct TCPIO_BlockCallbacks_Listener *_readListener;
    struct TCPIO_BlockCallbacks_Listener *_writeListener;
}

- (BOOL)withListeners:(CDUnknownBlockType)arg1;
- (void)setWriteListener:(struct TCPIO_BlockCallbacks_Listener *)arg1;
- (void)setReadListener:(struct TCPIO_BlockCallbacks_Listener *)arg1;
- (void)dealloc;
- (id)init;

@end

