//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface CNCDSmartGroupFetcher : NSObject
{
}

+ (id)smartGroupsMatchingPredicate:(id)arg1 contactStore:(id)arg2 persistenceStack:(id)arg3;
+ (id)smartGroupsInAccountsWithIdentifiers:(id)arg1 contactStore:(id)arg2 withPersistenceStack:(id)arg3;

@end

