//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Contacts/CNPostalAddress.h>

@class NSString;

@interface CNMutablePostalAddress : CNPostalAddress
{
}

@property(copy) NSString *subAdministrativeArea;
- (id)freeze;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(copy) NSString *ISOCountryCode; // @dynamic ISOCountryCode;
@property(copy) NSString *city; // @dynamic city;
@property(copy) NSString *country; // @dynamic country;
@property(copy) NSString *postalCode; // @dynamic postalCode;
@property(copy) NSString *state; // @dynamic state;
@property(copy) NSString *street; // @dynamic street;

@end

