//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <SafariServices/_SFActivityViewController.h>

@interface _SFManagedActivityViewController : _SFActivityViewController
{
    _Bool sourceIsManaged;
}

@property(nonatomic) _Bool sourceIsManaged; // @synthesize sourceIsManaged;
- (id)initWithActivityItems:(id)arg1 applicationActivities:(id)arg2 sourceURL:(id)arg3;

@end

