//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

__attribute__((visibility("hidden")))
@interface ABActionAddressMapsHelper : NSObject
{
}

+ (BOOL)isMapsReachable;
+ (void)mapAddressDictionary:(id)arg1 directions:(BOOL)arg2 fallbackURL:(id)arg3;
+ (void)mapAddress:(id)arg1 directions:(BOOL)arg2;
+ (void)mapAddressDictionary:(id)arg1 directions:(BOOL)arg2;

@end

