//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AddressBook/ABCNFetchRequest.h>

@class NSPredicate;

@interface ABCNGroupFetchRequest : ABCNFetchRequest
{
    NSPredicate *_predicate;
    BOOL _mutableObjects;
}

@property(nonatomic) BOOL mutableObjects; // @synthesize mutableObjects=_mutableObjects;
@property(copy, nonatomic) NSPredicate *predicate; // @synthesize predicate=_predicate;
- (void)executeFetchWithDataMapper:(id)arg1 observer:(id)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;

@end

