//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AddressBook/ABCollectionViewItem.h>

@class ABCollectionItemMessagingAvailabilityHelper;

__attribute__((visibility("hidden")))
@interface ABEmailCollectionViewItem : ABCollectionViewItem
{
    ABCollectionItemMessagingAvailabilityHelper *_messagingHelper;
}

- (BOOL)shouldShowGlyphButton:(id)arg1;
- (void)didRemoveFromCollection:(id)arg1;
- (void)didInsertIntoCollectionView:(id)arg1;
- (void)dealloc;
- (id)init;

@end

