//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ABPersonListAttributedName : NSObject
{
}

+ (id)italicFont;
+ (id)boldFont;
+ (id)normalFont;
+ (id)noNameString;
+ (BOOL)shouldEmphasizeRange:(struct _NSRange)arg1 ofName:(id)arg2;
+ (id)attributedStringForName:(id)arg1 emphasisRange:(struct _NSRange)arg2;

@end

