//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <IMCore/IMMessageStatusChatItem.h>

@class NSString;

@interface IMMessageEffectControlChatItem : IMMessageStatusChatItem
{
    NSString *_effectStyleID;
}

@property(readonly, copy, nonatomic) NSString *effectStyleID; // @synthesize effectStyleID=_effectStyleID;
- (void).cxx_destruct;
- (id)_initWithItem:(id)arg1 effectStyleID:(id)arg2;

@end

