//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CNContactCardViewControllerContactFetcher : NSObject
{
}

+ (id)observerWithCompletionHandler:(CDUnknownBlockType)arg1;
+ (void)finishObserver:(id)arg1 withResult:(id)arg2 error:(id)arg3;
+ (id)fetchContactWithIdentifier:(id)arg1 unified:(BOOL)arg2 keysToFetch:(id)arg3 fetchAsynchronously:(BOOL)arg4 completionHandler:(CDUnknownBlockType)arg5;

@end

