//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, NSString;

__attribute__((visibility("hidden")))
@interface BRCVolume : NSObject
{
    struct statfs _stfs;
    _Bool _isCaseSensitive;
    _Bool _isIgnoringOwnership;
    int _deviceID;
}

@property(readonly, nonatomic) _Bool isIgnoringOwnership; // @synthesize isIgnoringOwnership=_isIgnoringOwnership;
@property(readonly, nonatomic) _Bool isCaseSensitive; // @synthesize isCaseSensitive=_isCaseSensitive;
@property(readonly, nonatomic) int deviceID; // @synthesize deviceID=_deviceID;
@property(readonly, nonatomic) NSNumber *totalSize;
@property(readonly, nonatomic) NSNumber *freeSize;
- (id)description;
@property(readonly, nonatomic) NSString *fsTypeName;
@property(readonly, nonatomic) NSString *mountPath;
- (_Bool)setUpForRelPath:(id)arg1 session:(id)arg2 error:(id *)arg3;

@end

