//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <GeoServices/GEOMapRequest.h>

@class GEOMapTileFinder;

__attribute__((visibility("hidden")))
@interface GEOMapBuildingFinder : GEOMapRequest
{
    GEOMapTileFinder *_tileFinder;
    CDStruct_2c43369c _centerCoordinate;
    double _radius;
}

- (void)findBuildingsWithHandler:(CDUnknownBlockType)arg1;
- (void)cancel;
- (void)dealloc;
- (id)initWithMap:(id)arg1 centerCoordinate:(CDStruct_c3b9c2ee)arg2 radius:(double)arg3;

@end

