//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NWSnapshotSource;

@interface NWSnapshotter : NSObject
{
    unsigned long long _kernelSourceRef;
    NWSnapshotSource *_snapshotSource;
}

@property(retain) NWSnapshotSource *snapshotSource; // @synthesize snapshotSource=_snapshotSource;
@property unsigned long long kernelSourceRef; // @synthesize kernelSourceRef=_kernelSourceRef;
- (void).cxx_destruct;
- (id)snapshot;

@end

