//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <iLifeMediaBrowser/ILImagePreview.h>

@interface ILMediaBrowserImagePreviewView : ILImagePreview
{
}

- (BOOL)acceptsFirstMouse:(id)arg1;
- (id)animationForKey:(id)arg1;
- (void)keyDown:(id)arg1;

@end

