//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class AVAssetWriterInputHelper, AVAssetWriterInputPassDescriptionResponder, AVKeyPathDependencyManager, AVWeakReference;

@interface AVAssetWriterInputInternal : NSObject
{
    AVWeakReference *weakReference;
    AVAssetWriterInputHelper *helper;
    struct dispatch_queue_s *helperQueue;
    BOOL attachedToPixelBufferAdaptor;
    BOOL attachedToMetadataAdaptor;
    AVWeakReference *weakReferenceToAssetWriter;
    AVKeyPathDependencyManager *keyPathDependencyManager;
    long long numberOfAppendFailures;
    struct dispatch_queue_s *appendFailureReadWriteQueue;
    AVAssetWriterInputPassDescriptionResponder *passDescriptionResponder;
}

@end

