//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AVFoundation/AVCaptureOutputSettings.h>

@class AVAudioOutputSettings;

@interface AVCaptureAudioSettings : AVCaptureOutputSettings
{
    AVAudioOutputSettings *_avAudioOutputSettings;
}

@property(readonly, nonatomic) AVAudioOutputSettings *avAudioOutputSettings; // @synthesize avAudioOutputSettings=_avAudioOutputSettings;
- (id)outputSettingsDictionary;
- (void)dealloc;
- (id)initWithTrustedAudioSettingsDictionary:(id)arg1;
- (id)initWithAudioSettingsDictionary:(id)arg1;

@end

