//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class AVContentKeySessionInternal, NSArray, NSData, NSURL;
@protocol AVContentKeySessionDelegate;

@interface AVContentKeySession : NSObject
{
    AVContentKeySessionInternal *_session;
}

+ (void)removePendingExpiredSessionReports:(id)arg1 withAppIdentifier:(id)arg2 storageDirectoryAtURL:(id)arg3;
+ (id)pendingExpiredSessionReportsWithAppIdentifier:(id)arg1 storageDirectoryAtURL:(id)arg2;
- (void)processContentKeyRequestInitializationData:(id)arg1 options:(id)arg2;
@property(readonly) NSData *contentProtectionSessionIdentifier;
- (void)expire;
@property(readonly) NSArray *streamDataParsers;
- (void)removeStreamDataParser:(id)arg1;
- (void)addStreamDataParser:(id)arg1;
@property(readonly) NSURL *storageURL;
@property(readonly, nonatomic) id <AVContentKeySessionDelegate> delegate;
- (void)setDelegate:(id)arg1;
- (void)dealloc;
- (void)finalize;
- (void)_willDeallocOrFinalize;
- (id)initWithStorageDirectoryAtURL:(id)arg1;
- (id)init;
- (int)createProtectorSessionIdentifierIfNecessary:(const struct __CFData **)arg1;
- (int)createProtectorIfNecessary:(struct OpaqueFigCPEProtector **)arg1;
- (int)createDecryptorIfNecessaryForKeyRequestInitializationData:(id)arg1 decryptor:(const struct OpaqueFigCPECryptor **)arg2;
- (int)createDecryptorIfNecessaryForKeyRequestInitializationData:(id)arg1 withFormatDescription:(struct opaqueCMFormatDescription *)arg2 decryptor:(const struct OpaqueFigCPECryptor **)arg3;
- (int)setAppIdentifier:(id)arg1;
- (id)contentKeyRequestWithInitializationData:(id)arg1;
- (struct OpaqueFigCPECryptor *)copyDecryptorForKeyRequestInitializationData:(id)arg1;
- (BOOL)hasProtector;

@end

