//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MBLocale : NSObject
{
}

+ (id)_preferredKeyboardSourceIDsForLocaleIdentifier:(id)arg1;
+ (id)AMDLanguageCodeForISOLanguageCode:(id)arg1;
+ (id)currentISOLanguageCode;
+ (id)systemISOCountryCode;
+ (void)setSystemLocale:(id)arg1;
+ (void)setSystemCountryWithISOCode:(id)arg1;
+ (BOOL)configureGlobalLanguageUserDefaults;

@end

