//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CloudPhotoLibrary/CPLPlatformImplementation-Protocol.h>

@class NSDictionary, NSString;

@protocol CPLEngineStorageImplementation <CPLPlatformImplementation>
- (BOOL)_checkSuperWasCalled;
- (NSDictionary *)statusDictionary;
- (NSString *)status;
- (void)writeTransactionDidSucceed;
- (void)writeTransactionDidFail;
- (BOOL)closeWithError:(id *)arg1;
- (BOOL)openWithError:(id *)arg1;
@end

