//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/_NSThemeWidgetCell.h>

@interface _NSThemeCloseWidgetCell : _NSThemeWidgetCell
{
    BOOL _edited;
}

- (BOOL)setEditedFlag:(BOOL)arg1;
- (BOOL)isEdited;
- (int)getState:(id)arg1;
- (BOOL)accessibilityIsEditedAttributeSettable;
- (id)accessibilityEditedAttribute;
- (id)accessibilityAttributeNames;

@end

