//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSBrowserCell.h>

@interface NSLazyBrowserCell : NSBrowserCell
{
}

+ (id)lazyBrowserCell;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (void)initialize;
- (void)setControlView:(id)arg1;
- (BOOL)_isLoaded;
- (BOOL)isLoaded;
- (void)setLoaded:(BOOL)arg1;
- (void)_clearMouseTracking;
- (void)dealloc;
- (unsigned long long)retainCount;
- (oneway void)release;
- (id)retain;
- (id)init;

@end

