//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface IDMapping : NSObject
{
    NSString *_localId;
    NSString *_globalId;
}

+ (id)mappingFromGlobalId:(id)arg1 toLocalId:(id)arg2;
- (void)dealloc;
- (id)description;
- (void)setLocalId:(id)arg1;
- (id)globalId;
- (id)localId;
- (id)initMappingFromGlobalId:(id)arg1 toLocalId:(id)arg2;

@end

