//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CalDelegateFoldersPermissions : NSObject
{
    int _calendarPermission;
    int _taskPermission;
}

@property(nonatomic) int taskPermission; // @synthesize taskPermission=_taskPermission;
@property(nonatomic) int calendarPermission; // @synthesize calendarPermission=_calendarPermission;
- (id)initWithCalendarPermission:(int)arg1 taskPermission:(int)arg2;

@end

