//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface CalDAVKerberosPrincipals : NSObject
{
    NSString *clientPrincipal;
    NSString *servicePrincipal;
}

@property(copy) NSString *servicePrincipal; // @synthesize servicePrincipal;
@property(copy) NSString *clientPrincipal; // @synthesize clientPrincipal;
- (void)dealloc;
- (id)description;

@end

