//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CalendarPersistence/CalManagedObject.h>

@class CalManagedCalDAVCalendar, CalManagedPrincipal, NSURL;

@interface CalManagedCalendarUserAddress : CalManagedObject
{
}

+ (id)preferredAddressURLforAddresses:(id)arg1;
+ (id)entityName;
- (id)enclosingSource;
@property(retain) NSURL *address;
- (void)willRefresh:(BOOL)arg1;

// Remaining properties
@property(retain) CalManagedCalDAVCalendar *calendar; // @dynamic calendar;
@property(retain) CalManagedPrincipal *principal; // @dynamic principal;

@end

