//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ISDevice : NSObject
{
}

+ (id)eosDeviceType;
+ (BOOL)hasTouchIDAndEnrolled;
+ (BOOL)isTouchIDCapable;
+ (BOOL)isBootedFromRecoveryPartition;
+ (id)osMajorVersionString;
+ (void)osVersionReturningMajor:(int *)arg1 minor:(int *)arg2 point:(int *)arg3;
+ (long long)availableDiskSpace;
+ (long long)availableSpaceOnDiskAtPath:(id)arg1;
+ (id)guid;

@end

