//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface WPNodeManager : NSObject
{
    NSMutableDictionary *mNodes;
}

+ (id)sharedManager;
- (void)removeNodesForSession:(id)arg1;
- (id)nodeForPath:(id)arg1 session:(id)arg2 error:(out id *)arg3;
- (id)nodeInfoForPath:(id)arg1 session:(id)arg2 error:(out id *)arg3;
- (void)setNodeInfo:(id)arg1 forPath:(id)arg2 session:(id)arg3;
- (id)nodesForSession:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)init;

@end

