//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import <MIME/NSCacheDelegate-Protocol.h>

@class MFWeakReferenceHolder, NSCache, NSRecursiveLock, NSString;
@protocol MFLazyCacheDelegate;

@interface MFLazyCache : NSObject <NSCacheDelegate>
{
    NSRecursiveLock *_lock;
    NSCache *_storage;
    MFWeakReferenceHolder *_delegate;
    struct {
        unsigned int delegateRespondsToLazyCacheWillEvictObject:1;
    } _flags;
}

- (void)cache:(id)arg1 willEvictObject:(id)arg2;
- (id)valueForKey:(id)arg1 valueGenerator:(CDUnknownBlockType)arg2;
- (void)_exchangeOriginalValue:(id)arg1 forKey:(id)arg2 withValue:(id)arg3;
- (void)removeAllObjects;
@property __weak id <MFLazyCacheDelegate> delegate;
- (void)dealloc;
- (id)init;
- (id)storedValueForKey:(id)arg1;
- (long long)waiterCountForKey:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

