//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIStatusBarForegroundStyleAttributes.h>

__attribute__((visibility("hidden")))
@interface UIStatusBarExternalForegroundStyleAttributes : UIStatusBarForegroundStyleAttributes
{
}

- (id)textForNetworkType:(int)arg1;
- (double)textOffsetForStyle:(long long)arg1;
- (id)makeTextFontForStyle:(long long)arg1;
- (long long)activityIndicatorStyleWithSyncActivity:(_Bool)arg1;
- (struct UIEdgeInsets)edgeInsetsForBluetoothBatteryInsides;
- (struct UIEdgeInsets)edgeInsetsForBatteryInsides;
- (double)edgePadding;
- (double)standardPadding;
- (_Bool)usesVerticalLayout;
- (double)scale;

@end

