//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MCDBrowserViewController, MPAVController, MPCMediaPlayerLegacyPlayer, RadioRecentStationsController, UIWindow;
@protocol MCDCarDisplayServiceProvider;

@interface MCDRootController : NSObject
{
    UIWindow *_carDisplayWindow;
    MCDBrowserViewController *_browserViewController;
    MPCMediaPlayerLegacyPlayer *_legacyPlayer;
    MPAVController *_player;
    id <MCDCarDisplayServiceProvider> _serviceProvider;
}

@property(readonly, nonatomic) UIWindow *carDisplayWindow; // @synthesize carDisplayWindow=_carDisplayWindow;
@property(nonatomic) __weak id <MCDCarDisplayServiceProvider> serviceProvider; // @synthesize serviceProvider=_serviceProvider;
@property(retain, nonatomic) MPAVController *player; // @synthesize player=_player;
@property(retain, nonatomic) MPCMediaPlayerLegacyPlayer *legacyPlayer; // @synthesize legacyPlayer=_legacyPlayer;
- (void).cxx_destruct;
- (void)reloadRadio;
@property(nonatomic) __weak RadioRecentStationsController *recentStationsController;
- (void)showNowPlaying:(_Bool)arg1;
- (void)dealloc;
- (void)screenDidDisconnect;
- (id)initWithScreen:(id)arg1 hostTabBarController:(id)arg2;

@end

