//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MusicCarDisplayUI/MCD_OLD_TableViewController.h>

#import <MusicCarDisplayUI/MCDErrorViewDelegate-Protocol.h>
#import <MusicCarDisplayUI/MCDRadioContentManagerDelegate-Protocol.h>

@class MPModelRadioStation, MPWeakTimer, NSArray, NSIndexPath, NSString, UIActivityIndicatorView, UINavigationController, UIView;

@interface MCDRadioViewController : MCD_OLD_TableViewController <MCDRadioContentManagerDelegate, MCDErrorViewDelegate>
{
    NSArray *_featuredStations;
    NSArray *_recentStations;
    MPModelRadioStation *_prominentRadioStation;
    UIView *_placeholderView;
    UIView *_MCD_tableView;
    _Bool _recentStationsFinishedLoading;
    _Bool _featuredStationsFinishedLoading;
    _Bool _didInitiatePlayback;
    _Bool _radioStationsLoaded;
    NSIndexPath *_selectedIndexPath;
    UINavigationController *_nowPlayingNavigationController;
    UIActivityIndicatorView *_activityIndicator;
    id _currentlyPlayingRadioStation;
    unsigned long long _prominentStationIndex;
    unsigned long long _featuredStationsIndex;
    unsigned long long _allStationsIndex;
    MCD_OLD_TableViewController *_viewController;
    MPWeakTimer *_loadingTimer;
}

+ (_Bool)currentlyPlayingRadioStationFromStation:(id)arg1 nowPlayingItem:(id)arg2;
@property(retain, nonatomic) MPWeakTimer *loadingTimer; // @synthesize loadingTimer=_loadingTimer;
@property(nonatomic) _Bool radioStationsLoaded; // @synthesize radioStationsLoaded=_radioStationsLoaded;
@property(retain, nonatomic) MCD_OLD_TableViewController *viewController; // @synthesize viewController=_viewController;
@property(nonatomic) unsigned long long allStationsIndex; // @synthesize allStationsIndex=_allStationsIndex;
@property(nonatomic) unsigned long long featuredStationsIndex; // @synthesize featuredStationsIndex=_featuredStationsIndex;
@property(nonatomic) unsigned long long prominentStationIndex; // @synthesize prominentStationIndex=_prominentStationIndex;
@property(retain, nonatomic) id currentlyPlayingRadioStation; // @synthesize currentlyPlayingRadioStation=_currentlyPlayingRadioStation;
@property(nonatomic) _Bool didInitiatePlayback; // @synthesize didInitiatePlayback=_didInitiatePlayback;
@property(nonatomic) _Bool featuredStationsFinishedLoading; // @synthesize featuredStationsFinishedLoading=_featuredStationsFinishedLoading;
@property(nonatomic) _Bool recentStationsFinishedLoading; // @synthesize recentStationsFinishedLoading=_recentStationsFinishedLoading;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) UINavigationController *nowPlayingNavigationController; // @synthesize nowPlayingNavigationController=_nowPlayingNavigationController;
@property(retain, nonatomic) NSIndexPath *selectedIndexPath; // @synthesize selectedIndexPath=_selectedIndexPath;
- (void).cxx_destruct;
- (id)_stationFromIndexPath:(id)arg1;
- (id)_filteredRadioStations:(id)arg1;
- (void)_categorizeStations;
- (void)errorViewDidTapButton:(id)arg1;
- (void)_updateViewForNetworkType:(long long)arg1;
- (_Bool)_isNetworkTypeAllowed:(long long)arg1;
- (void)_itemDidChange;
- (id)viewControllerForRowAtIndexPath:(id)arg1;
- (void)didStartPlaying:(id)arg1;
- (void)_presentStationUnavailableAlertForError:(id)arg1 stationName:(id)arg2;
- (void)_startPlayingStation:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)_networkTypeDidChangeNotification:(id)arg1;
- (void)featuredStationsDidUpdate:(id)arg1;
- (void)recentStationsDidUpdate:(id)arg1;
- (void)_limitedUIDidChange;
- (void)dealloc;
- (void)_setCurrentTableView;
- (void)_showLoadingScreen;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)_reloadRadioStations;
- (id)initWithPlayer:(id)arg1 serviceProvider:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

