//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreFoundation/CFPrefsSource.h>

__attribute__((visibility("hidden")))
@interface CFPrefsPlistSource : CFPrefsSource
{
    struct dispatch_group_s *_synchGroup;
    struct __CFString *userIdentifier;
    struct __CFString *domainIdentifier;
    struct __CFString *container;
    struct __CFDictionary *_locallySetDict;
    const char *accessPath;
    struct {
        unsigned int _isByHost:1;
        unsigned int _volatile:1;
        unsigned int _readonly:1;
        unsigned int _avoidsDaemonCache:1;
        unsigned int _restrictedAccess:1;
        unsigned int _checkedInvalidHome:1;
        unsigned int _lastWriteFailed:1;
    } _flags;
}

- (void)finalize;
- (void)dealloc;
- (void)_sharedCleanup;
- (long long)generationCount;
- (long long)alreadylocked_generationCount;
- (BOOL)synchronize;
- (BOOL)volatilizeIfInvalidHomeDir;
- (void)alreadylocked_clearCache;
- (void)sendRequestNewDataMessage:(void *)arg1 toConnection:(struct _xpc_connection_s *)arg2 retryCount:(int)arg3 error:(char *)arg4;
- (void)handleReply:(void *)arg1 toRequestNewDataMessage:(void *)arg2 onConnection:(struct _xpc_connection_s *)arg3 retryCount:(int)arg4 error:(char *)arg5;
- (void *)createRequestNewContentMessageForDaemon:(BOOL)arg1;
- (BOOL)alreadylocked_requestNewData;
- (long long)sendMessageSettingValue:(void *)arg1 forKey:(struct __CFString *)arg2;
- (void)sendFullyPreparedMessage:(void *)arg1 settingValue:(void *)arg2 forKey:(struct __CFString *)arg3 retryCount:(int)arg4;
- (void)addPIDImpersonationIfNecessary:(void *)arg1;
- (BOOL)attachAccessTokenToMessage:(void *)arg1 accessType:(int)arg2;
- (BOOL)handleErrorReply:(void *)arg1 fromMessageSettingKey:(struct __CFString *)arg2 toValue:(void *)arg3 retryCount:(int)arg4 retryContinuation:(CDUnknownBlockType)arg5;
- (BOOL)handleErrorReply:(void *)arg1 retryCount:(int)arg2 retryContinuation:(CDUnknownBlockType)arg3;
- (void)goReadOnlyAfterTryingToWriteKey:(struct __CFString *)arg1 value:(void *)arg2;
- (void)goVolatileAfterTryingToWriteKey:(struct __CFString *)arg1 value:(void *)arg2;
- (void)_goReadOnlyOrVolatileAfterTryingToWriteKey:(struct __CFString *)arg1 value:(void *)arg2;
- (void *)createSynchronizeMessage;
- (void)alreadylocked_setValue:(void *)arg1 forKey:(struct __CFString *)arg2;
- (id)description;
- (struct __CFDictionary *)alreadylocked_copyDictionary;
- (struct __CFArray *)alreadylocked_copyKeyList;
- (void *)copyValueForKey:(struct __CFString *)arg1;
- (void)mergeIntoDictionary:(struct __CFDictionary *)arg1;
- (void *)alreadylocked_copyValueForKey:(struct __CFString *)arg1;
- (void)setDaemonCacheEnabled:(BOOL)arg1;
- (void)setAccessRestricted:(BOOL)arg1;
- (id)initWithDomain:(struct __CFString *)arg1 user:(struct __CFString *)arg2 byHost:(BOOL)arg3 containerPath:(struct __CFString *)arg4;
- (BOOL)isByHost;
- (struct __CFString *)container;
- (void)setContainer:(struct __CFString *)arg1;
- (void)setDomainIdentifier:(struct __CFString *)arg1;
- (struct __CFString *)domainIdentifier;
- (void)setUserIdentifier:(struct __CFString *)arg1;
- (struct __CFString *)userIdentifier;

@end

