//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber, SAGuidanceGuideSnippet, SAGuidanceGuideUpdate;
@protocol OS_dispatch_queue;

@interface SiriUIGuideCacheManager : NSObject
{
    SAGuidanceGuideUpdate *_cachedGuideUpdate;
    NSObject<OS_dispatch_queue> *_cacheFileQueue;
}

+ (id)sharedManager;
- (void).cxx_destruct;
- (id)_aceObjectDictionaryAtFilepath:(id)arg1;
- (id)_cachedGuideUpdate;
- (id)_pathForCachedGuideUpdate;
- (void)_updateLastCheckedWithDate:(id)arg1;
- (BOOL)_shouldCheckForUpdateAtDate:(id)arg1;
- (void)clearCachedGuide;
- (void)updateCacheWithGuideUpdate:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updateLastCheckedDate;
- (BOOL)shouldCheckForUpdate;
@property(readonly, nonatomic) SAGuidanceGuideSnippet *cachedGuideSnippet;
@property(readonly, nonatomic) NSNumber *cachedGuideTag;
- (id)init;

@end

