//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSCollectionViewItem.h>

@interface SiriUICollectionViewItem : NSCollectionViewItem
{
    BOOL _remainsVisibleOnDrag;
}

+ (id)reuseIdentifier;
@property BOOL remainsVisibleOnDrag; // @synthesize remainsVisibleOnDrag=_remainsVisibleOnDrag;
- (BOOL)_isTranscriptCollectionViewItem;
- (id)accessibilityIdentifier;
- (id)accessibilityParent;
- (BOOL)isAccessibilityElement;
- (void)setSelected:(BOOL)arg1;
- (void)setHighlightState:(long long)arg1;
- (id)draggingImageComponents;
- (void)_setDragging:(BOOL)arg1;
- (void)prepareForReuse;

@end

