//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 19 2016 22:08:00).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CallKit/CXAudioSessionActivationStateObserver-Protocol.h>

@class CXAction, CXTransaction;

@protocol CXProviderVendorProtocol <CXAudioSessionActivationStateObserver>
- (oneway void)handleActionTimeout:(CXAction *)arg1;
- (oneway void)commitTransaction:(CXTransaction *)arg1;
@end

